### ISSUE TITLE
支付宝移动支付签名问题

### ISSUE THREAD

**Issue by guandaxia** [helei112g/payment#1]
支付宝移动支付接口，签名算法不需要排序，只要求保持请求参数的顺序和待签名参数的顺序一致。可是我看代码在计算签名的时候进行了排序，返回参数的时候却没有排序，我想问一下，这样是不是会有问题？

**Comment by helei112g** [comment]
官方只是说可以不用排序。没说不能排序。

1. 这部分进行排序一个目的是为了能够统一这部分加密算法。

2. 就算排序加密后不会影响任何支付流程。

非常细心哦。
