### ISSUE TITLE
网络发生错误，请稍后再试curl返回码：1

### ISSUE THREAD

**Issue by denghp** [helei112g/payment#10]
网络发生错误，请稍后再试curl返回码：1

为啥出现这种情况？

使用的是PHP-7.0.3

**Comment by helei112g** [comment]
helei5200@126.com
 可以参考本处的错误码含义。修正自己的环境。
http://www.cnblogs.com/wainiwann/p/3492939.html
发件人： denghp
发送时间： 2016-11-27 21:21
收件人： helei112g/payment
主题： [helei112g/payment] 网络发生错误，请稍后再试curl返回码：1 (#10)
网络发生错误，请稍后再试curl返回码：1
为啥出现这种情况？
使用的是PHP-7.0.3

**Comment by levivi** [comment]
怎么解决的啊
