### ISSUE TITLE
微信在支付后回调notify.php  $ret返回的同时需要修改订单状态需要在$retData取数据吗？这个地方能不能友好一点

### ISSUE THREAD

**Issue by leiliang520130** [helei112g/payment#100]

**Comment by helei112g** [comment]
你所谓的友好是怎么个友好法？

**Comment by leiliang520130** [comment]
你的 notify.php  $ret 微信回调的时候只有微信需要的xml，没有我的订单id，而上面的$retData又没有验证
，我希望是

![a 8](https://user-images.githubusercontent.com/15342190/33128556-b1946664-cfc7-11e7-9df7-91f06712a0d9.png)

帮我返回一下需要的数据如我的订单号

**Comment by helei112g** [comment]
新版本已经提供你想要的功能。请更新payment版本
