### ISSUE TITLE
是否考虑接入有赞？

### ISSUE THREAD

**Issue by bestony** [helei112g/payment#102]
有赞 API  https://github.com/xu42/open-sdk-php

官方地址：https://www.youzanyun.com/docs/guide/3399/3411

**Comment by helei112g** [comment]
暂无计划

**Comment by bolechen** [comment]
有赞跟 Payment 不是一个东西吧

**Comment by bestony** [comment]
@bolechen 新出来的有赞云，可以个人接入：https://blog.xu42.cn/2017/11/26/person-website-instant-payment-solution/
