### ISSUE TITLE
微信支付报错，支付宝支付正常

### ISSUE THREAD

**Issue by hjldev** [helei112g/payment#103]
Argument 2 passed to Payment\ChargeContext::initCharge() must be of the type array, boolean given, called in D:\webhome\dianhanji\vendor\riverslei\payment\src\Client\Charge.php on line 54 and defined[D:\webhome\dianhanji\vendor\riverslei\payment\src\ChargeContext.php:48
直接调用微信支付报错，支付宝支付正常

**Comment by hjldev** [comment]
直接使用demo也是报错
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@phpStudy.net to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by hjldev** [comment]
已解决。

**Comment by tiandaye** [comment]
请问下怎么解决的。Internal Server Error
