### ISSUE TITLE
关于私钥直接设置内容太长问题

### ISSUE THREAD

**Issue by edwinfound** [helei112g/payment#108]
如果rsa_private_key直接设置内容而不是路径的话，会出现以下错误：

`file_exists(): File name is longer than the maximum allowed path length on this platform (1024)`

平台：OSX
PHP：5.6

**Comment by helei112g** [comment]
怎么才能更合理的区分填写的是密钥还是是密钥的文件名称呢？
难道增加一个长度检测吗？

**Comment by edwinfound** [comment]
我也在想要不要增加一个参数，或者，干脆直接强制文件路径好了，
这个问题是今天配置支付宝的接口私钥遇到的，
问题不是很大，不知道大家有没有什么完美的解决办法。

PS：还是感谢这个开源SDK，真的很好用哇。

**Comment by helei112g** [comment]
增加太多参数会变得越来越复杂，没有必要。长度检测应该是ok的。文件名正常情况下不可能有1000个字符吧？
