### ISSUE TITLE
支付宝现在版本是不是不支持统一收单api

### ISSUE THREAD

**Issue by lpwang1031** [helei112g/payment#110]
我想使用支付宝内置浏览器打开我们得wap网页,然后在支付宝内部完成支付,咨询官方给得答复是只能签约当面付,然后调用统一收单接口,然后再调用jsapi完成支付宝内置浏览器支付,我读了几遍文档好像没有找到这个统一收单得文档,请问是暂时不支持这个功能是吧？
alipay统一收单接口:https://docs.open.alipay.com/api_1/alipay.trade.create

**Comment by helei112g** [comment]
是的，payment没用到这个接口。
