### ISSUE TITLE
关于异步通知

### ISSUE THREAD

**Issue by imdgr** [helei112g/payment#111]
文档里看不到。不知道是不是文档坏掉了

**Comment by imdgr** [comment]
我看了下源码，请问callback的参数是 `原始数据转成数组` 吗

**Comment by helei112g** [comment]
还没有写完。真是不好意思，😄

**Comment by imdgr** [comment]
看了源码和文档，已经清楚了。感谢你和这个库，支付宝接入一次成功。
等我有时间了，可以一起完善文档

**Comment by helei112g** [comment]
表示特别感谢。
