### ISSUE TITLE
message: "Undefined index: mweb_url"

### ISSUE THREAD

**Issue by tiandaye** [helei112g/payment#112]
微信支付的时候我遇到了这个问题。`message: "Undefined index: mweb_url",`

**Comment by tiandaye** [comment]
我使用微信的h5支付, 返回字段在 `return_code` 和 `result_code` 都为 `SUCCESS` 的时候有返回 `trade_type`  （值为MWEB）和 `prepay_id` 字段。没有返回 `mweb_url` 字段。

**Comment by helei112g** [comment]
你有微信 h5 支付的权限吗？

**Comment by tiandaye** [comment]
`wap` 吗？ 好像没有，所以没有返回来这个字段。我只能用 `jssdk` ?

**Comment by helei112g** [comment]
是的。后面这里我增加个错误返回。

本来腾讯应该返回没有权限的错误，但是不知道为什么他们没有处理。

**Comment by tiandaye** [comment]
我用您的支付宝秘钥, 用 `ali_wap` 类型, 可以调出h5支付界面，支付宝显示要输入手机号码，但是输入手机号没有发送给我短信。调支付宝客户端的时候, 提示 `操作已超时, 请重新发起支付`。 谢谢!
