### ISSUE TITLE
我用您的支付宝秘钥，调支付宝客户端的时候, 提示 操作已超时, 请重新发起支付

### ISSUE THREAD

**Issue by tiandaye** [helei112g/payment#114]
我用您的支付宝秘钥, 用 ali_wap 类型, 可以调出h5支付界面，支付宝显示要输入手机号码，但是输入手机号没有发送给我短信。调支付宝客户端的时候, 提示 操作已超时, 请重新发起支付。 谢谢!

**Comment by helei112g** [comment]
支付宝我的秘钥是沙箱环境，需要支付宝的沙箱 app 配合才行。

**Comment by tiandaye** [comment]
谢谢哈! 我们公司的支付宝和微信的秘钥没有申请下来, 所以我只能用你的测试。
