### ISSUE TITLE
body，subject含有特殊字符时候，总是提示签名错误，应该怎样处理呢？

### ISSUE THREAD

**Issue by indiboy** [helei112g/payment#115]
转码了也不行，不知道怎么回事。
比如说！~~
诺基亚 7 (Nokia 7) 4GB+64GB 黑色 全网通 双卡双待

**Comment by helei112g** [comment]
有些特殊字符是第三方（支付宝、微信）所不准许的，按照他们规定来

**Comment by indiboy** [comment]
多谢老大回复，具体说不清什么问题。这样修改之后就正常了。
'body' => strip_tags($order_list['intro']),
'subject' => strip_tags($order_list['title']),
