### ISSUE TITLE
微信H5支付bug

### ISSUE THREAD

**Issue by duxphp** [helei112g/payment#117]
微信H5支付目前开放申请，使用时不返回任何数据 通过调试 报错为
`
<xml><return_code><![CDATA[FAIL]]></return_code><return_msg><![CDATA[XML格式错误]]></return_msg></xml>
`

**Comment by duxphp** [comment]
因证书原因 有些接口无法返回数据 在更换了Guzzle后改原因一直存在  影响到除公众号支付外的其他微信支付 app wap

**Comment by helei112g** [comment]
什么意思？意思是只有公众号支付是正常的？

**Comment by duxphp** [comment]
是的 你可以测试下 只有公众号js支付是正常的   其他微信支付类都不返回内容

**Comment by helei112g** [comment]
我这里正常，无法复现你说的情况。
