### ISSUE TITLE
支付宝企业付款，付款成功，签名验证不通过

### ISSUE THREAD

**Issue by fastgoo** [helei112g/payment#129]
### 这里是支付请求处理方法

```
protected function sendReq($url)
{
    // 发起网络请求
    $curl = new Curl();
    $responseTxt = $curl->set([
        'CURLOPT_SSL_VERIFYPEER'    => true,
        'CURLOPT_SSL_VERIFYHOST'    => 2,
        'CURLOPT_HEADER'    => 0,// 为了便于解析，将头信息过滤掉
        //'CURLOPT_CAINFO'    => $this->config->cacertPath,
    ])->get($url);

    if ($responseTxt['error']) {
        throw new PayException('网络发生错误，请稍后再试curl返回码：' . $responseTxt['message']);
    }

    $body = $responseTxt['body'];

    $responseKey = str_ireplace('.', '_', $this->config->method . '.response');

    $body = json_decode($body, true);
    if ($body[$responseKey]['code'] != 10000) {
        throw new PayException($body[$responseKey]['sub_msg']);
    }

    // 验证签名，检查支付宝返回的数据
    $flag = $this->verifySign($body[$responseKey], $body['sign']);
    if (! $flag) {
        throw new PayException('支付宝返回数据被篡改。请检查网络是否安全！');
    }

    return $body[$responseKey];
}
```

通过打印 $body 发现其实已经支付成功，但是在 $this-&gt;verifySign\($body\[$responseKey\], $body\['sign'\]\) 这一步的时候返回false，导致异常。目前可以通过支付宝支付接口支付，签名配置有看到异常问题

### 这是我的调用方法

```
public static function pay($data = array())
{
    $data = [
        'trans_no' => $data['order_no'],
        'payee_type' => 'ALIPAY_LOGONID',
        'payee_account' => $data['account'],
        'amount' => $data['amount'],
        'remark' => $data['remark'],
    ];
    try {
        $ret = Transfer::run('ali_transfer', AliPay::config(), $data);
        return $ret;
    } catch (PayException $e) {
        return $e->getMessage();
    }
}


/**
 * @param array $data
 * @return array
 */
public static function config($data = array())
{
    /** 重组配置参数 */
    $self = new self();
    $config = $self->di->get("commonConfig")->alipay->toArray();
    return [
        'use_sandbox' => !empty($config['use_sandbox']) ? $config['use_sandbox'] : false,// 是否使用沙箱环境
        'partner' => $config['partner'],
        'app_id' => $config['app_id'],
        'sign_type' => 'RSA2',// RSA  RSA2
        'ali_public_key' => $config['ali_public_key'],
        'rsa_private_key' => $config['rsa_private_key'],
        'limit_pay' => [],//'balance'余额、moneyFund'余额宝、'debitCardExpress'借记卡快捷、'creditCard'信用卡、'creditCardExpress'信用卡快捷、'creditCardCartoon'信用卡卡通、'credit_group'信用支付类型（包含信用卡卡通、信用卡快捷、花呗、花呗分期）
        'notify_url' => !empty($data['notify_url']) ? $data['notify_url'] : 'http://baidu.com',
        'return_url' => !empty($data['return_url']) ? $data['return_url'] : '',
        'return_raw' => false,// 在处理回调时，是否直接返回原始数据，默认为 true
    ];
}

```

**Comment by helei112g** [comment]
这种一般是本地支付宝公钥配置错误




From: HeLei


在2018年01月26日 10:02，周建军<notifications@github.com> 写道：
这里是支付请求处理方法
protected function sendReq($url)
{
    // 发起网络请求
    $curl = new Curl();
    $responseTxt = $curl->set([
        'CURLOPT_SSL_VERIFYPEER'    => true,
        'CURLOPT_SSL_VERIFYHOST'    => 2,
        'CURLOPT_HEADER'    => 0,// 为了便于解析，将头信息过滤掉
        //'CURLOPT_CAINFO'    => $this->config->cacertPath,
    ])->get($url);

    if ($responseTxt['error']) {
        throw new PayException('网络发生错误，请稍后再试curl返回码：' . $responseTxt['message']);
    }

    $body = $responseTxt['body'];

    $responseKey = str_ireplace('.', '_', $this->config->method . '.response');

    $body = json_decode($body, true);
    if ($body[$responseKey]['code'] != 10000) {
        throw new PayException($body[$responseKey]['sub_msg']);
    }

    // 验证签名，检查支付宝返回的数据
    $flag = $this->verifySign($body[$responseKey], $body['sign']);
    if (! $flag) {
        throw new PayException('支付宝返回数据被篡改。请检查网络是否安全！');
    }

    return $body[$responseKey];
}


通过打印 $body 发现其实已经支付成功，但是在 $this->verifySign($body[$responseKey], $body['sign']) 这一步的时候返回false，导致异常。目前可以通过支付宝支付接口支付，签名配置有看到异常问题

这是我的调用方法
public static function pay($data = array())
{
    $data = [
        'trans_no' => $data['order_no'],
        'payee_type' => 'ALIPAY_LOGONID',
        'payee_account' => $data['account'],
        'amount' => $data['amount'],
        'remark' => $data['remark'],
    ];
    try {
        $ret = Transfer::run('ali_transfer', AliPay::config(), $data);
        return $ret;
    } catch (PayException $e) {
        return $e->getMessage();
    }
}


/**
 * @param array $data
 * @return array
 */
public static function config($data = array())
{
    /** 重组配置参数 */
    $self = new self();
    $config = $self->di->get("commonConfig")->alipay->toArray();
    return [
        'use_sandbox' => !empty($config['use_sandbox']) ? $config['use_sandbox'] : false,// 是否使用沙箱环境
        'partner' => $config['partner'],
        'app_id' => $config['app_id'],
        'sign_type' => 'RSA2',// RSA  RSA2
        'ali_public_key' => $config['ali_public_key'],
        'rsa_private_key' => $config['rsa_private_key'],
        'limit_pay' => [],//'balance'余额、moneyFund'余额宝、'debitCardExpress'借记卡快捷、'creditCard'信用卡、'creditCardExpress'信用卡快捷、'creditCardCartoon'信用卡卡通、'credit_group'信用支付类型（包含信用卡卡通、信用卡快捷、花呗、花呗分期）
        'notify_url' => !empty($data['notify_url']) ? $data['notify_url'] : 'http://baidu.com',
        'return_url' => !empty($data['return_url']) ? $data['return_url'] : '',
        'return_raw' => false,// 在处理回调时，是否直接返回原始数据，默认为 true
    ];
}

**Comment by fastgoo** [comment]
我试试，看是不是支付宝的公钥有问题

**Comment by fastgoo** [comment]
确实是支付宝的公钥的问题
