### ISSUE TITLE
微信退款返回Undefined index: refund_channel

### ISSUE THREAD

**Issue by isszz** [helei112g/payment#130]
src/Refund/WxRefund.php

微信并没有返回这3个变量
$data['refund_channel']
$data['coupon_refund_fee']
$data['coupon_refund_count']

**Comment by helei112g** [comment]
在配置文件里边设置：return_raw = true

我发现这个返回值跟申请的主体好像有关系，我这边确实是有的。

**Comment by isszz** [comment]
好的谢谢

**Comment by isszz** [comment]
@helei112g 但是出现一个问题,返回原始数据后,异步通知的就不能用一套代码实现了- -...
