### ISSUE TITLE
支付宝wap  交易订单处理失败

### ISSUE THREAD

**Issue by zuozhehao** [helei112g/payment#134]
支付宝wap 支付,跳转到新版支付宝APP,提示 交易订单处理失败,(ALI38173).

使用支付宝账号密码登录则正常支付,也能收到异步通知

**Comment by helei112g** [comment]
是跳转到支付宝app报错，但是使用h5通过账号密码，就正确，是这个意思吗？

**Comment by zuozhehao** [comment]
对的

**Comment by helei112g** [comment]
无法复现该问题，如果依然村子啊，请提供更多信息。
例如：支付宝版本、是否具备相关权限等等
