### ISSUE TITLE
支付宝验签不通过

### ISSUE THREAD

**Issue by ncwsky** [helei112g/payment#135]
使用4.0的版本
使用扫码支付时，支付宝返回的签名验证始终不通过，异步通知也是这样。
公钥 和 私钥 我都换了好几遍了
 'ali_public_key'=>'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq5UlI0kQklYO9QOWakEILFhH2D7chYF+bAMLdw0PXHiiq315lbKUDNe0oZUmV5HaZm5eupHqyAD8IbjFcXG6ylNBQ5//rXBZe8jwtxr+1Di3zXTr5yEwNUS+FjRLTDVbd5gyM2NieJISOIqIHNdUWgE2xVvmr/KBOZSwjPWN8VUuB8DM1Mb/ZQBN7YQOIKD88HV2u2dGkv69tRPeeLQIblqHXpgrnlEnBgML7VziYnP9x9yfeipdVLndPiessOrVsLelPi7YHwZSUSEZ4ei9Fp2X+NwvWmQbrJCWJdzDhAYA/Ompeq+zPWBaO3g2UPBp6s7QuSMp6GlkHcrr4ivOUwIDAQAB',
            'rsa_private_key'=>'MIIEpAIBAAKCAQEAq5UlI0kQklYO9QOWakEILFhH2D7chYF+bAMLdw0PXHiiq315lbKUDNe0oZUmV5HaZm5eupHqyAD8IbjFcXG6ylNBQ5//rXBZe8jwtxr+1Di3zXTr5yEwNUS+FjRLTDVbd5gyM2NieJISOIqIHNdUWgE2xVvmr/KBOZSwjPWN8VUuB8DM1Mb/ZQBN7YQOIKD88HV2u2dGkv69tRPeeLQIblqHXpgrnlEnBgML7VziYnP9x9yfeipdVLndPiessOrVsLelPi7YHwZSUSEZ4ei9Fp2X+NwvWmQbrJCWJdzDhAYA/Ompeq+zPWBaO3g2UPBp6s7QuSMp6GlkHcrr4ivOUwIDAQABAoIBAGf5r1GcmyAyaknrbKDi27MTpCXUogl9GUEW70Grdl2Q9PJ6zMz8NF8778fi/CMgzXo488qXVfDxN9ivgWZnhsvIe8ohEOznIjKy57vt7fJolGk6qyGaqP3+tDn8YozB4LWuUu11El0CF2yP9j+T9Re9mJUsRbTlfY2JHxusSeGtwHYvmYV4+DZ643xJBbZH0Zp8SP6jFJ25y3RT7uskNdn7Huf+eqrqoeHhiDeXYL+qMCo3wahTLLV/MeKY8B6KX+my5ZtRkWTYBUJbXG29H7V8Oye5HqRu4lTraVwFws+oHL4XFHx4g0My5I3P0L4S2N1hlRrxv44YLMNZeXDS5NECgYEA1Pn/ttpdKbQPaixTZgii4hGzWXW8abDqjYhlISl0+tbq4FgrJfxANvOU3i9YC8yQ79GCKneTQATzhq5h6nc+Hf7SKBhoHRA/c0FrzhzHHAwa8sRJ2h58+8NUpiQM7jEYc61guMWkZTrzvS/PsWJVV774ntdzBn3QH+CS5a4k580CgYEAzj55MCRznzZeMJWfxjosO+KTN0hZOLIuiD1/d/6IsyA6kdK7cNx45SlyWujCU0WdO0nh3UtfyZku9k9YT/cb8sd/nozAXskmY4n5Pt7rKcWGUMMKk3EPcksZrmO4gYdNi2oK2d17ARi6C6Sb1G0Kv/gfj6ScvstAy356Pwr9Lp8CgYEAuhaij3Om+VxiJ6QJTtr2708GBYGxGixCFV569onRs6b73QBM20jYFuuoRKbbaJvafCD0egS2/bYVzrUpywNbnDveBrikp9hdiGg+OP6+HsyY80v9N39yN00J9o0DW1A8jD6Oh4Pxy53CAKj48YX5Cc1MUQXxdFeT9XZ1BAiwKHUCgYABNiq+Fqi7ObWJ8YcTwgm6fFVDEOC9TYaqdDoIeW1SKBFQA/3n5tOq/PhYAmAJ3zHSRFfYVfYFGCpHdiXdqmT2oydjxg3nQKVCFnBpZyPYhfmJBexM+3AMytYmyR0vXZ0eAYx4xS1Qz1VgdiIYOF/Eyu9ch6oIEOebim2rayQbnwKBgQC9dr/Ac6wgsBPu63Sxh+FCVz1x/6FoAaZHrUHw47gxp+3/3Kpsxmih8GsCXeTOw1vxG6RkN1JfnqmBGY+PkAuwvpvfIvfa2KROE7J0s5OP1C1Ode8S33e1WckAHpK5Ki36JbrHl2p08yJxESJglqhZjwUOK+6aHJdn0bB7LSf0eg==',
            

这是在生成扫码支付时返回的结果
在线支付订单生成失败,支付宝返回数据被篡改。请检查网络是否安全！{\"alipay_trade_precreate_response\":{\"code\":\"10000\",\"msg\":\"Success\",\"out_trade_no\":\"9000000120180222093817608026\",\"qr_code\":\"https:\\/\\/qr.alipay.com\\/bax001447gxdqhwdtnzv20dd\"},\"sign\":\"dGLzbHvfvwzAYEGgcQPuYA6C5pT1VU5jWi0XlpdMbgtAKeTpKrGm0XQtV\\/ok+zmxnvwugvxm8\\/BrCd8MwRZ8AnwcLZes4DaL0zEI67Ey407pNeJpt3Jq3d6sF2tXE9sP7YWAGTjKTON5Kb9XSOUOEV1NCicmC6CySwnr9b3Kdp0GgtU9GQGh61MQC25bdTaIO4WlidpHsunGtxP9eGhbRtsavfBkR8WeAjUBN\\/9cQBxKlFjhd8izV1QlqGHOCp0DhMxZ78zJ5RlFVpfiXLJGZo29VXGjA9OLWcZROMUqF8tWTnmHZsT4dSCtEeVuGMbZ61aga6T1YOujjDyxiCGgLw==\"}

**Comment by helei112g** [comment]
检查自己的支付宝公钥。
