### ISSUE TITLE
建议使用foreach代替each函数

### ISSUE THREAD

**Issue by Choate** [helei112g/payment#139]
由于php 7.2 之后的版本打算把each废除，目前运行在PHP 7.2的版本都会产生Warning。

**Comment by helei112g** [comment]
4.x的版本，我应该去掉 each 了吧？还有？可以指出路径

**Comment by Choate** [comment]
`Payment\Utils\ArrayUtil::createLinkstring`
`Payment\Utils\ArrayUtil::paraFilter`

**Comment by Choate** [comment]
4.0.x 版本并未做修复，README上的安装教程应该修改一下。

使用该教程安装的小伙伴只能安装最高4.0.1版本的库，并没有办法安装最新版本的库。

**Comment by helei112g** [comment]
4.1以后已经修改了。
