### ISSUE TITLE
mbstring扩展已经安装但是composer require不了，提示 mbstring * -> no matching package found.

### ISSUE THREAD

**Issue by KOMKZ** [helei112g/payment#14]
Problem 1
    - Installation request for riverslei/payment ^2.7.0 -> satisfiable by riverslei/payment[v2.7.0].
    - riverslei/payment v2.7.0 requires mbstring * -> no matching package found.

我的扩展已经装了，2.7.0中的composer.json中的依赖是不是要改成
ext-mbstring : *
fork之后重打了标签，改成上述的样子就可以正常安装了。

参考：
https://getcomposer.org/doc/02-libraries.md#platform-packages

**Comment by helei112g** [comment]
非常感谢。已修正。
