### ISSUE TITLE
微信支付配置上面的app_cert_pem,app_key_pem 哪里获取？

### ISSUE THREAD

**Issue by hungryandfoolishboy** [helei112g/payment#140]

**Comment by xzs1994** [comment]
这个可以网上找，主要功能是为了验证。这里配置是获取对应文件的地址，但要注意此地址是绝对路径。

**Comment by helei112g** [comment]
微信商户后台可下载

**Comment by Paladinhanxiao** [comment]
问一下问题，我一个项目pem可以使用相对路径，但是另一个项目却只能使用绝对路径。有人知道为什么吗？

**Comment by gh0sthx** [comment]
> 
> 
> 这个可以网上找，主要功能是为了验证。这里配置是获取对应文件的地址，但要注意此地址是绝对路径。
问一下问题，我一个项目pem可以使用相对路径，但是另一个项目却只能使用绝对路径。有人知道为什么吗？
