### ISSUE TITLE
请问一下小程序收不到微信支付成功的回调有可能是什么原因？

### ISSUE THREAD

**Issue by byenic** [helei112g/payment#142]
require_once $_SERVER['DOCUMENT_ROOT'] . C('ROOT_PATH'). '/lib/new_payment/vendor/autoload.php';
require_once $_SERVER['DOCUMENT_ROOT'] . C('ROOT_PATH'). '/lib/new_payment/examples/PayNotify.php';

date_default_timezone_set('Asia/Shanghai');

$aliConfig = require_once $_SERVER['DOCUMENT_ROOT'] . C('ROOT_PATH'). '/lib/new_payment/examples/aliconfig.php';
$wxConfig = require_once $_SERVER['DOCUMENT_ROOT'] . C('ROOT_PATH'). '/lib/new_payment/examples/wxconfig.php';
$cmbConfig = require_once $_SERVER['DOCUMENT_ROOT'] . C('ROOT_PATH'). '/lib/new_payment/examples/cmbconfig.php';

$callback = new PayNotify();

$from = $_GET['from'] ? $_GET['from'] : 'wx';

if ($from === 'ali') {
//
} elseif ($from === 'wx') {

    $config = $wxConfig;
    $type = 'wx_charge';
} else {
    $config = $cmbConfig;
    $type = 'cmb_charge';
}

try {
    //$retData = Notify::getNotifyData($type, $config);// 获取第三方的原始数据，未进行签名检查
    $ret = Notify::run($type, $config, $callback);// 处理回调，内部进行了签名检查
} catch (PayException $e) {
    echo $e->errorMessage();
    exit;
}

var_dump($ret);
exit;

这里是设置的notify的URL=> "https://xxx.cc/lib/new_payment/examples/pay_notify.php",

**Comment by jaredwu** [comment]
签名的二次验证 有问题
