### ISSUE TITLE
为什么异步通知一直验证不通过呢

### ISSUE THREAD

**Issue by websw** [helei112g/payment#144]
//使用获取数据是可以成功返回的
$retData = Notify::getNotifyData($type, $config);

//验签 跑不到业务处理类里，所有设置都正确，并且成功支付，支付宝也有通知返回
$ret = Notify::run($type, $config, $callback);

**Comment by helei112g** [comment]
签名没有通过。检查自己的支付宝公钥

**Comment by helei112g** [comment]
#142 
#135 
#129

**Comment by Aexus** [comment]
> //使用获取数据是可以成功返回的
> $retData = Notify::getNotifyData($type, $config);
> 
> //验签 跑不到业务处理类里，所有设置都正确，并且成功支付，支付宝也有通知返回
> $ret = Notify::run($type, $config, $callback);

请问这个问题怎么解决了?现在做电脑网站支付宝支付,也不跑 验签 里面.直接获取原始数据是正确的,难道是因为加密方式是 RSA2?

**Comment by Aexus** [comment]
> //使用获取数据是可以成功返回的
> $retData = Notify::getNotifyData($type, $config);
> 
> //验签 跑不到业务处理类里，所有设置都正确，并且成功支付，支付宝也有通知返回
> $ret = Notify::run($type, $config, $callback);

检查是地址是不是带参数了.我就是因为这个问题,找了好久,后来发现是这个问题造成的!
