### ISSUE TITLE
微信返回错误提示问题

### ISSUE THREAD

**Issue by lscho** [helei112g/payment#154]
代码中为`throw new PayException('微信返回错误提示:' . $retData['ret_msg']);`
提示ret_msg不存在，调试发现，微信的接口返回的格式为
```
Array
(
    [return_code] => FAIL
    [retmsg] => 请确认请求参数是否正确mch_id
    [retcode] => 1
)
```
请问是否是微信接口更新导致？

**Comment by helei112g** [comment]
这个问题已经反馈给微信支付团队了，他们文档有错误，我是按照文档开发的
今天排查一下
