### ISSUE TITLE
Undefined index: return_code

### ISSUE THREAD

**Issue by gyf19** [helei112g/payment#160]
level: 8
    message: 'Undefined index: return_code'
    file: '/vendor/riverslei/payment/src/Notify/WxNotify.php'
    line: 66
    context: array(
        'data' => array(
            'value' => array(
                'xxe' => array(
                    'xxe' => array(),
                ),
            ),
        ),
    )

**Comment by gyf19** [comment]
是不是被盯上了?

**Comment by helei112g** [comment]
最近会对代码进行重构，确保稳定性。预计4月完成
