### ISSUE TITLE
Undefined index: trade_status

### ISSUE THREAD

**Issue by scfobao** [helei112g/payment#163]
Severity: Notice

Message: Undefined index: trade_status

Filename: Notify/AliNotify.php

Line Number: 74

Backtrace:

File: /var/www/html/bus_plat/api/vendor/riverslei/payment/src/Notify/AliNotify.php
Line: 74
Function: _error_handler

File: /var/www/html/bus_plat/api/vendor/riverslei/payment/src/Notify/NotifyStrategy.php
Line: 49
Function: checkNotifyData

File: /var/www/html/bus_plat/api/vendor/riverslei/payment/src/NotifyContext.php
Line: 81
Function: handle

File: /var/www/html/bus_plat/api/vendor/riverslei/payment/src/Client/Notify.php
Line: 66
Function: notify

**Comment by helei112g** [comment]
是否尝试过设置：return_raw=true ?
