### ISSUE TITLE
部分文档看不到

### ISSUE THREAD

**Issue by wuliaowyh** [helei112g/payment#169]
回调通知查询的文档看不到了，文档网站证书过期了

**Comment by helei112g** [comment]
应该是被墙了，最近找个时间重新整理一版文档

**Comment by linzhoulxyz** [comment]
> 应该是被墙了，最近找个时间重新整理一版文档

搭梯子也一样看不到，包括最后那张核心类图的下载链接也是错的。

**Comment by wuliaowyh** [comment]
估计证书过期了

**Comment by helei112g** [comment]
图看不到发现是由于七牛把我的免费域名移除了。后期文档重建
