### ISSUE TITLE
微信支付报 网络环境未能通过安全验证，请稍后再试，怎么获取真实IP

### ISSUE THREAD

**Issue by shohanshohan** [helei112g/payment#172]
$this->client_ip = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1';

这个简单的方法好像不能获取到IP和微信端是一样的，可以微信又没有php的demo说明，用了多个获取IP的方法还是不能满足微信出现这个报错！

**Comment by helei112g** [comment]
检查下你们是否有设置代理
