### ISSUE TITLE
bcdiv 函数需要 BC 函数库支持，但未在文档中说明

### ISSUE THREAD

**Issue by BruceFan-FS71** [helei112g/payment#18]
bcdiv 函数 需要在 PHP 编译的时候使用 --enable-bcmath 开启方可使用，但 readme 中并未说明需要 BC 函数库，建议加入。

又或者是使用其他的方式来代替 bcdiv 函数，毕竟一般的生产环境上很少使用到 BC 函数库的，而 PHP 的编译，还是尽量以精简为目的的好。

**Comment by helei112g** [comment]
好的，非常感谢建议。浮点型的数据为了确保精度，因此采用了该种方式。
文档中会增加相关说明。当前已经在 composer 中进行了约束。

**Comment by Tony-Lee** [comment]
+1
传到服务器上页面空白, 最后发现错误提示
PHP Fatal error:  Call to undefined function Payment\\Common\\Ali\\Data\\Charge\\bccomp()
