### ISSUE TITLE
订单未支付情况下，有些字段未定义

### ISSUE THREAD

**Issue by browningweb** [helei112g/payment#180]
https://github.com/helei112g/payment/blob/80c29cb2591accc170f95f34f066cd7258f07f35/src/Query/Wx/WxChargeQuery.php#L77

订单未支付状态下，返回的数据为：
`array (
            'return_code' => 'SUCCESS',
            'return_msg' => 'OK',
            'appid' => 'xxxxx',
            'mch_id' => '123123',
            'nonce_str' => 'xxx',
            'sign' => 'qww',
            'result_code' => 'SUCCESS',
            'out_trade_no' => 'qwqw',
            'trade_state' => 'NOTPAY',
            'trade_state_desc' => '订单未支付',
        );`

有些字段未定义，报错。

**Comment by helei112g** [comment]
接下来会处理
