### ISSUE TITLE
'trade_status' => 'TRADE_CLOSED'

### ISSUE THREAD

**Issue by awebc** [helei112g/payment#183]
支付宝未支付的订单，到期自动关闭时，支付宝会异步通知，其中POST的数据 'trade_status' => 'TRADE_CLOSED',看了下您的源代码，好像除了成功的状态，其余全部return了，没有继续验证，正确应该 是继续下去的，业务方可以关闭订单的

**Comment by helei112g** [comment]
下个版本修改
