### ISSUE TITLE
laravel 5.7 Class 'Payment\Client\Charge not found

### ISSUE THREAD

**Issue by ftlh2005** [helei112g/payment#184]
很奇怪服务器上提示
`{
    "msg": "Class 'Payment\\Client\\Charge' not found",
    "code": 500
}`

本地开发环境又是正常的

**Comment by helei112g** [comment]
应该是服务器上 composer autoload的问题

**Comment by freefreego** [comment]
在调用 Charge::run 的时候 ，我也遇到了这样的情况
 Class 'Payment\\Client\\Charge' not found 
请帮忙看一下，已执行composer require "riverslei/payment:*"

**Comment by paulycode** [comment]
riverslei/payment 版本问题 看测试代码

**Comment by Scyllaly** [comment]
旧版本BUG，升级到laravel 6.x 就会出现这个问题，已经通过更换 ominipay解决了

**Comment by paulycode** [comment]
嗯 以前用的老的支付包

scyllaly <notifications@github.com> 于2020年8月5日周三 下午11:34写道：
