### ISSUE TITLE
支付宝即时到帐接口  新版本，不再支持该方式，这个什么意思啊。

### ISSUE THREAD

**Issue by indiboy** [helei112g/payment#19]
就是打开支付宝PC网页支付吗，在学习支付，没有相应帐号，不知道怎么玩。
即时到帐接口就是打开PC网页的那个支付是吗？

**Comment by helei112g** [comment]
支付宝的新版本，没有提供即时到账接口。如果你要使用即时到账接口，使用老版本的配置

**Comment by indiboy** [comment]
明白了，就是说新版的支付宝本身没有即时到账接口，用的话要用老版本的支付本身接口。
payment-v1有即时到账
payment-v2你没有做即时到账这个功能，因为用的新版的支付宝接口，没法用旧版的接口整合？

**Comment by helei112g** [comment]
@indiboy 是的。因为新老版本使用的支付宝账号体系不同，如果同时整合更难理解。但是你可以自己进行组合。没有限制。相当于多个配置文件而已。
