### ISSUE TITLE
支付宝支付如果没有开通二维码支付异常处理错误

### ISSUE THREAD

**Issue by chic900709** [helei112g/payment#193]
`   protected function retData(array $ret)
    {
        $url = parent::retData($ret);

        // 发起网络请求
        try {
            $data = $this->sendReq($url);
        } catch (PayException $e) {
            throw $e;
        }

        // 检查是否报错
        if ($data['code'] !== '10000') {
           //new PayException($data['sub_msg']); 源码
            throw new PayException($data['sub_msg']);//修改成这样
        }
        return $data['qr_code'];
    }`

**Comment by chic900709** [comment]
文件位置在payment/src/Charge/Ali/AliQrCharge.php 49行

**Comment by helei112g** [comment]
收到，感谢
