### ISSUE TITLE
支付宝应用公钥证书模式-需要如何配置？

### ISSUE THREAD

**Issue by aikunzhe** [helei112g/payment#194]
![image](https://user-images.githubusercontent.com/9932394/67468515-37431980-f67d-11e9-89f7-2be95e4ee18e.png)
支付宝资金支出类接口（转账，现金红包）只能使用证书方式。

**Comment by wjq310** [comment]
我也在关注这个问题，发现 rsaAliPubKey 这个参数根本没法填

**Comment by wjq310** [comment]
这个作者能否来回复下呢，很急呀，这个功能应该是不支持的

**Comment by helei112g** [comment]
这是支付宝的新功能，没有上线。有时间我加一下
