### ISSUE TITLE
支付成功后的回调没有判断成功与否吗

### ISSUE THREAD

**Issue by yh414209726** [helei112g/payment#196]
Fatal error: Class 'GuzzleHttp\Client' not found in /opt/lampp/htdocs/wuyus/src/Common/Ali/AliBaseStrategy.php on line 109

**Comment by wjq310** [comment]
要compose 安装，不然没办法关联到， 我这边是 compose 开发的，都报了 Call to undefined function GuzzleHttp\\json_decode()  值

**Comment by helei112g** [comment]
是的，需要用到composer install
