### ISSUE TITLE
微信扫码支付如何生成二维码？

### ISSUE THREAD

**Issue by act2009** [helei112g/payment#197]
返回的结果$ret 打印出来是一个url(weixin://wxpay/s/An4baqw)，但是使用跳转的话显示下图结果：
![image](https://user-images.githubusercontent.com/48006419/70117912-a1e66c80-16a1-11ea-8fd1-97c38e1aedfc.png)

**Comment by act2009** [comment]
发现返回的url值一直没有变，生成二维码也没用

**Comment by helei112g** [comment]
生成二维码你可以使用一些在线api，比如：腾讯自己就有提供，或者一些开源的类库都可以

**Comment by act2009** [comment]
> 生成二维码你可以使用一些在线api，比如：腾讯自己就有提供，或者一些开源的类库都可以

这个使用qrcode就可以，但是返回的url每次都一样，扫码也失效

**Comment by helei112g** [comment]
每次肯定会变化
