### ISSUE TITLE
请问下能兼容下5.4环境么

### ISSUE THREAD

**Issue by 349865361** [helei112g/payment#2]
因为项目为商业项目 需要兼容大部分环境 最低环境为5.4 使用payment中有几个语法的支持不支持5.4 请问可以做兼容么 目前是自己修改了不兼容的部分

**Comment by helei112g** [comment]
可以自己修复不兼容部分。但是带来的一个问题是：你以后不能通过composer进行及时更新。否则更新会覆盖你修复的部分。
