### ISSUE TITLE
你好，我看版本里有3.x, 4.x, 5.x，那么master是哪个版本？？为什么版本跨度这么大

### ISSUE THREAD

**Issue by nottellyou** [helei112g/payment#203]
我看版本里有3.x, 4.x, 5.x，那么master是哪个版本？？为什么版本跨度这么大？？

可否解释一下。

**Comment by helei112g** [comment]
master当前是 `5.x` 版本；
`3.x` 的版本是最初，缺少了很多东西在 `4.x`进行了修正，导致无法小版本兼容；`5.x` 主要是重构了项目的结构。也无法向前兼容

**Comment by bolechen** [comment]
有没有 3.x -> 4.x -> 5.x 的 ChangeLog? 方便旧项目升级用？感谢！
