### ISSUE TITLE
微信小程序支付签名错误

### ISSUE THREAD

**Issue by zhudewei1985** [helei112g/payment#206]
你好，反馈一下，最新版5.x的微信小程序支付签名算法有误。
最多5个参数，参与签名算法。我用以下代码通过测试。

//签名要自己做，集成的SDK 5.x有BUG
        $param = [
            'appId' => $this->wxconfig['app_id'],
            'nonceStr' => $ret['nonce_str'],
            'package' => 'prepay_id=' . $ret['prepay_id'],
            'signType' => $this->wxconfig['sign_type'],
            'timeStamp' => TIMENOW,
        ];  
        $signStr = http_build_query($param, PHP_QUERY_RFC3986, '&');  
        $signStr = str_replace('%3D', '=', $signStr);  
        $signStr .= '&key=' . $this->wxconfig['md5_key'];  
        $sign = strtoupper(hash_hmac('sha256', $signStr, $this->wxconfig['md5_key']));

**Comment by helei112g** [comment]
你这个签名方式是从哪里来的呢？我看微信文档并没有说明需要 http_build_query并进行替换。

**Comment by zhudewei1985** [comment]
我是参考 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5  编写的，http_build_query只是把array转换为key=value&key1=value1的形式，不是必须的，如果是自己写foreach也可以的。我之前开发过程中，不管用什么参数进行签名，都是可以通过签名验证工具的，但是那个签名结果，在实际小程序响起支付时，会失败。最后改为5个参数生成签名，就可以了。

**Comment by zhudewei1985** [comment]
> 你这个签名方式是从哪里来的呢？我看微信文档并没有说明需要 http_build_query并进行替换。
> 
> https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=4_3

我是参考 https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5 编写的，http_build_query和手写foreach效果一样的，替换是因为http_build_query会把prepay_id=编码为prepay_id%3D 导致签名前的字符串有误。

**Comment by helei112g** [comment]
这个与我参考的文档是一致。
你确定只有小程序有问题？其它正常？

**Comment by zhudewei1985** [comment]
> 这个与我参考的文档是一致。
> 你确定只有小程序有问题？其它正常？

我只用小程序支付，其它的没试过。

**Comment by helei112g** [comment]
目前我这里并不能复现（不知道是否跟我用的测试账号有关系）；我会持续关注这个问题
