### ISSUE TITLE
微信支付回调验签失败

### ISSUE THREAD

**Issue by daifangyun** [helei112g/payment#208]
微信支付回调验签失败，WxNotify.php 中verifySign方法，删除一位数组中'sign', 'sign_type'的值，官方文档有提到将所有返回数据除了sign值参与生成签名，部分回调数据中包含了sign_type的值，若删掉的话，会报验签失败。

**Comment by daifangyun** [comment]
版本4.x

**Comment by helei112g** [comment]
建议使用最新的版本。老版本的话可以提个 pr 给我
