### ISSUE TITLE
微信公众号JSAPI支付的时候签名错误

### ISSUE THREAD

**Issue by a5962109** [helei112g/payment#209]
$client = new \Payment\Client(\Payment\Client::WECHAT, $config);
            $res    = $client->pay(\Payment\Client::WX_CHANNEL_PUB, $payData);
            $res['timeStamp'] =  strval( time() );
            $this->writeJson(Status::CODE_OK, $res, 'success');

         这里不知道已经二次加签了 还是没有二次加签过
         没有二次加签的时候  掉起来报  签名错误
         自己手动加签以后     报total_fee未设置

**Comment by a5962109** [comment]
后续：我自己重写了签名生成算法，终于可以通过了，应该是JSAPI签名生成算法有问题导致的

**Comment by helei112g** [comment]
应该是这个问题：#211
