### ISSUE TITLE
微信支付回调验签失败

### ISSUE THREAD

**Issue by cyfx** [helei112g/payment#211]
最近发现我们生产的项目经常有用户支付成功后，但是没有执行回调，经验证是微信支付回调返回的xml，有部分包含sign_type字段，但是在验签的时候，**payment会去掉sign_type,导致验签失败**。
旧版本的4.*，新版本的5.*都会出现。
如下是微信返回的xml，脱敏后的数据，
`<xml><appid><![CDATA[wx48dd*****3da6]]><\/appid>\n<attach><![CDATA[123]]><\/attach>\n<bank_type><![CDATA[OTHERS]]><\/bank_type>\n<cash_fee><![CDATA[1000]]><\/cash_fee>\n<device_info><![CDATA[WEB]]><\/device_info>\n<fee_type><![CDATA[CNY]]><\/fee_type>\n<is_subscribe><![CDATA[N]]><\/is_subscribe>\n<mch_id><![CDATA[150****371]]><\/mch_id>\n<nonce_str><![CDATA[bdmtmfy9f891****cf6q3opfzu]]><\/nonce_str>\n<openid><![CDATA[ouGhb1S*****vkE]]><\/openid>\n<out_trade_no><![CDATA[20041112213431109]]><\/out_trade_no>\n<result_code><![CDATA[SUCCESS]]><\/result_code>\n<return_code><![CDATA[SUCCESS]]><\/return_code>\n<sign><![CDATA[3E57FF0A97AB76E7E82583267E782A06]]><\/sign>\n<sign_type><![CDATA[MD5]]><\/sign_type>\n<time_end><![CDATA[20200411122145]]><\/time_end>\n<total_fee>1000<\/total_fee>\n<trade_type><![CDATA[APP]]><\/trade_type>\n<transaction_id><![CDATA[42000*****11230]]><\/transaction_id>\n<\/xml>`

**Comment by helei112g** [comment]
感谢，已经修复！
