### ISSUE TITLE
关于支付宝新版签名方式

### ISSUE THREAD

**Issue by e282486518** [helei112g/payment#22]
在AliConfig.php中看到这样：
```php
        // 	新版只支持此种签名方式   商户生成签名字符串所使用的签名算法类型，目前支持RSA
        $this->signType = 'RSA';
```
但是在管理应用的时候支付宝推荐的是RSA2的签名方式参考：
https://doc.open.alipay.com/docs/doc.htm?treeId=291&articleId=106115&docType=1

https://doc.open.alipay.com/doc2/detail.htm?treeId=200&articleId=105310&docType=1

**Comment by helei112g** [comment]
你好，rsa2的支持，我正在开发中。之前我写的时候，RSA2官方还没有给出demo。所以没做。谢谢指正。

**Comment by helei112g** [comment]
3.0.0版本已发布。支付宝已经支付rsa2方式加密。
并且支付宝新增如下功能：
- 条码支付
- 支付宝转账
- 支付宝转账查询

微信新增如下功能：
- 刷卡支付
- 小程序支付
- H5支付
