### ISSUE TITLE
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in 

### ISSUE THREAD

**Issue by tablecell** [helei112g/payment#23]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in 
vendor\riverslei\payment\src\Charge\Wx\WxQrCharge.php on line 20
```
 
        return QrChargeData::class;
 
```

**Comment by helei112g** [comment]
请提供一下php版本信息。

**Comment by helei112g** [comment]
从错误信息看。是你的php版本不支持：QrChargeData::class;  这种语法特性
