### ISSUE TITLE
感谢，已经打赏。

### ISSUE THREAD

**Issue by greedying** [helei112g/payment#24]
不过文档有点少啊，没找到调用的例子

作为参考，作者可以看下[easywechat 文档](https://easywechat.org)

**Comment by helei112g** [comment]
感谢打赏，文档正在努力更新中。easywechat 写的很棒。

**Comment by greedying** [comment]
恩，在example里看到了部分例子。

**Comment by greedying** [comment]
请教一下，支付宝支付后，跳转回来的页面，怎么进行签名验证呢？谢谢，好像没找到。。

**Comment by helei112g** [comment]
同步通知没有提供一个统一的方法。但是你有两种实现方式，进行数据的验证。
1. 同步调回道你自己的方法时，内部通过实现 `PayNotifyInterface` 接口，可以实现验证签名
2. 实例化 
```
$ali = new AliNotify($aliConfi);

$retData = $ali->getNotifyData();

$flag = $ali->checkNotifyData($retData);// 内部实现了验证签名
```

通过 `$flag` 的结果，来判断签名是否正确。

推荐使用方式一。
