### ISSUE TITLE
报错提示

### ISSUE THREAD

**Issue by 349865361** [helei112g/payment#3]
环境: PHP 7.0.8

The magic method __get() must have public visibility and cannot be static line 58 in file /vendor/riverslei/payment/src/Common/BaseData.php

**Comment by helei112g** [comment]
非常抱歉，个人疏忽，导致该问题出现。

官方已说明：http://php.net/manual/zh/language.oop5.overloading.php#object.set

所有魔术方法必须是 `public`

在5.5  5.6 中测试 时未发现该问题。非常感谢你提出的bug。现已修复
