### ISSUE TITLE
支付宝回调验证失败

### ISSUE THREAD

**Issue by sanglongjia** [helei112g/payment#30]
您好：

根据您的示例，我集成到我们的项目中，正式环境配置，支付宝能够下单成功。并且也能够唤起手机APP进行支付，支付成功后。后台始终是FAIL，似乎无法验证签名。

**Comment by helei112g** [comment]
你好，可能是密钥设置错误，请对照该配置文档进行一下 支付宝公钥检查。

http://t.cn/R6aG2r0

另一种方式是，直接使用我的demo，sanbox方式测试一下。

**Comment by helei112g** [comment]
无法重现，本地测试异步通知验证签名正常，请检查设置的支付宝公钥是否正确

**Comment by chenggx** [comment]
你好 ，我也是出现了一样的问题，返回：返回数据验签失败，可能数据被篡改。想问下是什么原因
