### ISSUE TITLE
错误代码 ILLEGAL_SIGN 

### ISSUE THREAD

**Issue by ralphxlx** [helei112g/payment#31]
你好，我想问下在rsa 配置都正确下，为什么还提醒 错误代码 ILLEGAL_SIGN？

**Comment by helei112g** [comment]
请确认rsa是否正确，只能是密钥的问题

**Comment by ralphxlx** [comment]
> 请确认rsa是否正确，只能是密钥的问题
>
@helei112g 我是直接复制密钥到键值对，已去掉-----BEGIN PRIVATE KEY-----与-----END PRIVATE KEY-----，是即时到账接口，已通过支付宝提供的校检验证过是否匹配
`return['rsa_private_key'=>'xxxxxxxxx']`
