### ISSUE TITLE
请问该SDK支持PC 端支付吗？

### ISSUE THREAD

**Issue by wakerman** [helei112g/payment#33]
请问该SDK支持PC 端支付吗？ :)

**Comment by helei112g** [comment]
支付宝支持即时到账。

[即时到账](https://helei112g.github.io/2017/03/11/Payment%EF%BC%9A%E6%94%AF%E4%BB%98%E5%AE%9D%E5%8D%B3%E6%97%B6%E5%88%B0%E8%B4%A6%E6%8E%A5%E5%8F%A3%E6%8E%A5%E5%85%A5%E6%95%99%E7%A8%8B/)
