### ISSUE TITLE
Payment\Utils\ArrayUtil::paraFilter()为什么是===

### ISSUE THREAD

**Issue by lianghongle** [helei112g/payment#35]
Payment\Utils\ArrayUtil::paraFilter()
...if ($val === '') {continue;} ...
请问这里为什么是全等？我用的时候，全等生成的结果会有问题。改成‘==’就可以正常了。
请问这里改成全等的用意是什么？

**Comment by helei112g** [comment]
`===` 是为了只过滤 空字符，对于false  null不进行过滤。你哪种情况下遇到了问题？

**Comment by lianghongle** [comment]
paraFilter()这个方法传入的$para和返回的$paraFilter，我调试，用===和==，值都是一样的。但是用===的结果，无论是哪种支付方式，都是有问题的。换成==，就能正常使用。我也觉得很奇怪。没有头绪了。请问，你那边，用===还是==，都没有问题吗？
