### ISSUE TITLE
网络请求时，报错：curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by zhangvoice** [helei112g/payment#36]
设置 $channel = 'ali_qr';发生 网络发生错误，请稍后再试

**Comment by helei112g** [comment]
仅有这一种支付方式发生问题？

**Comment by zhangvoice** [comment]
ali_qr 和 ali_bar 吧

我在官方的demo 上使用，没有问题，二维码也能出来，只是使用手机时扫描出现码已过期，请重新刷新二维码重试的提示。具体原因未知。



zhangvoice@foxmail.com
 
发件人： 大愚
发送时间： 2017-04-24 14:46
收件人： helei112g/payment
抄送： zhangvoice; Author
主题： Re: [helei112g/payment] channel = 'ali_qr' 时 ，发生 网络发生错误，请稍后再试 (#36)
仅有这一种支付方式发生问题？

**Comment by helei112g** [comment]
可以断点获取一下  curl no的返回值。

**Comment by phpyii** [comment]
支付宝支付 为什么要设置 CURLOPT_SSL_VERIFYPEER => true  
https://github.com/helei112g/payment/blob/master/src/Common/Ali/AliBaseStrategy.php#L89  
这样 curl no值为60    就会提示 ：网络发生错误，请稍后再试

**Comment by helei112g** [comment]
设置 
```
 CURLOPT_SSL_VERIFYPEER => true
```
是为了采用 https 协议进行访问。如果你一直出现，检查下自己的服务器是否正常安装 ca 证书。

下面以nginx为例：
1. ca证书下载地址；  http://curl.haxx.se/ca/cacert.pem
2. 修改 php.ini 的 curl.cainfo 为该路径（绝对路径！），重启 php-fpm 服务即可。
> curl.cainfo = /path/to/downloaded/cacert.pem

 **这里的路径，请根据自己的实际情况填写。**

**Comment by zhangvoice** [comment]
谢谢，已确认错误为什么啦。谢谢来源。

**Comment by rundolph** [comment]
你好 我在使用支付宝转账的时候一直出现   "发生 网络发生错误，请稍后再试curl返回码：60",我断点打印的url是正确的，请问这是什么原因能，忘大神答复一下，谢谢了

**Comment by cyy199298** [comment]
你好，微信H5手机网站支付，echo输出的是一个链接地址，前台需要直接跳转吗？ 不是直接返回的是json的字符串吗，请求给我提示一下。谢谢

**Comment by luciferor** [comment]
错误代码 invalid-method 错误原因: 不存在的方法名，这个是什么原因呢？
