### ISSUE TITLE
请问扫码支付完成之后回调通知怎么验证，好像没有找到使用方法？

### ISSUE THREAD

**Issue by DarkiT** [helei112g/payment#37]
请问扫码支付完成之后回调通知怎么验证，好像没有找到使用方法？

**Comment by helei112g** [comment]
无论是微信支付，还是支付宝支付，在创建扫码支付的时候，都会先向微信或者支付宝发送一个请求，这个请求里边包含了对应的回调地址。

[支付宝扫码支付](https://doc.open.alipay.com/doc2/apiDetail.htm?spm=a219a.7629065.0.0.PlTwKb&apiId=862&docType=4)
[微信宝扫码支付](https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_1)

因此你支付成功后，第三方都会通过该接口告诉你结果。@DarkiT

**Comment by DarkiT** [comment]
我现在是通过您的SDK创建了当面付的二维码，然后扫码也支付成功了，支付宝也把支付结果POST到了我的回调接口上，但是我不知道如何验证这个数据的合法性，非程序员专业，您的代码也看的似懂非懂的，按您demo里面的教程，我这样$retData = Notify::getNotifyData('ali_charge', $config); 返回了支付宝给的数据，但是我不知道该如何验证数据的真实性，因为我发现直接往回调地址上POST数据也是能过验证的。琢磨了一个下午，还没没能搞明白。

**Comment by helei112g** [comment]
你使用的方法仅仅是拿到数据。请使用 *demo* 中这个方法替换。
```
$ret = Notify::run($type, $config, $callback);
```

该方法会自动进行数据签名验证，拿到回调的数据，直接进行你的业务逻辑处理即可。

**Comment by DarkiT** [comment]
经过您的指导，加上自己的实践摸索出来了，感谢！
