### ISSUE TITLE
微信公众号支付参数有误

### ISSUE THREAD

**Issue by 349865361** [helei112g/payment#4]
代码在 Common/Weixin/Data/Charge  40行

key是app_id而不是appid 不然API会报错
appid 或者 mch_id 不存在

但是改成了app_id了 后提示 微信返回错误提示: 
是空的

**Comment by 349865361** [comment]
自己没仔细检查

**Comment by helei112g** [comment]
你好。你说的是哪一版本？

发自我的 iPhone
