### ISSUE TITLE
处理Notify通知回调处理，的$data的amount和pay_amount都是null的？

### ISSUE THREAD

**Issue by cong5** [helei112g/payment#40]
根据你的文章[Payment：支付的回调统一处理](https://helei112g.github.io/2017/05/01/Payment%EF%BC%9A%E6%94%AF%E4%BB%98%E7%9A%84%E5%9B%9E%E8%B0%83%E7%BB%9F%E4%B8%80%E5%A4%84%E7%90%86/)来处理Notify通知，但是为什么Notify中的`$data`的`amount`和`pay_amount`都是null的？好多都是null，如下

```
INFO: array (
  'amount' => NULL,
  'buyer_id' => '2088xxxxxxxx',
  'transaction_id' => '2017xxxxxxxxxxxx69',
  'body' => '测试',
  'notify_time' => '2017-05-02 15:08:50',
  'subject' => '测试',
  'buyer_account' => NULL,
  'auth_app_id' => NULL,
  'notify_type' => 'trade_status_sync',
  'invoice_amount' => NULL,
  'order_no' => '2017xxxxxxx4120',
  'trade_state' => 'success',
  'pay_time' => '2017-05-02 15:08:49',
  'point_amount' => NULL,
  'trade_create_time' => '2017-05-02 15:08:47',
  'pay_amount' => NULL,
  'receipt_amount' => NULL,
  'fund_bill_list' => NULL,
  'app_id' => NULL,
  'seller_id' => '2088xxxxxxxx',
  'seller_email' => 'xxxxxxx@qq.com',
  'channel' => 'ali_charge',
)
```

**Comment by helei112g** [comment]
是即时到账吗？建议设置 `return_raw=true`  ,直接获取第三方返回的原始数据。`return_raw=false` 是返回的我映射后的数据，这里即时到账没有做处理。

**Comment by cong5** [comment]
@helei112g 是的，是即时到账的，好的。我试试，谢谢.

**Comment by helei112g** [comment]
预计 v3.1.1版本处理该问题，映射后的数据有个好处是，可以保障： 获取支付的金额跟订单号的字段是一致的，方便进行处理。 @cong5

**Comment by cong5** [comment]
@helei112g 是的。映射后就不用再额外单独针对支付平台进行单独的参数处理了。很期待 v3.1.1哦。

**Comment by jpyeah** [comment]
支付宝异步回调
 $ret = Notify::run($type, $config, $callback);
只返回一个fail是什么原因？
我用的版本是v3.1.1
 $retData = Notify::getNotifyData($type, $config);是可以打印出所有数据的

**Comment by helei112g** [comment]
检查签名信息

**Comment by helei112g** [comment]
支付宝的公钥
