### ISSUE TITLE
return_param参数问题

### ISSUE THREAD

**Issue by lianghongle** [helei112g/payment#42]
ali_app，需要用到return_param这个参数自定义一些参数。使用简单的字符串（aaa）可以使用，但是如果要使用多个键值的（a=1&b=2）时，应该怎么处理使用呢？

**Comment by helei112g** [comment]
&符号是特殊符号，不能使用。可以采用 | 、@ 进行分割。

**Comment by pokor** [comment]
能不能同时载入两个版本
3.1版没有退款功能呢
支付宝无密退款怎么弄呢?

**Comment by helei112g** [comment]
sdk 提供了无密码退款的接口，根据demo进行操作。
