### ISSUE TITLE
支付宝的新版电脑版支付兼容了吗？？

### ISSUE THREAD

**Issue by JKair** [helei112g/payment#43]
[这个](https://doc.open.alipay.com/docs/doc.htm?spm=a219a.7629140.0.0.qk9BoQ&treeId=270&articleId=105899&docType=1)

**Comment by phpyii** [comment]
不是早就兼容了吗 。 channel传ali_web就是pc即时到账

**Comment by JKair** [comment]
我看文档说明的好像是旧版的即时到账，不是新版的电脑支付。 @phpyii

**Comment by helei112g** [comment]
`更新时间：2017/05/05 访问次数：3227`

他们5月5号才发布的新版本。还没有做。之后添加。谢谢提醒。

**Comment by JKair** [comment]
@helei112g 不知道是不是我使用的方式不对，老版本的即时到账的异步通知，统一参数返回是存在大问题的，老版本的即时到账和手机支付是完全不同的。我自己私自修改了代码做参数兼容才能让异步通知正常运行。

**Comment by helei112g** [comment]
#42 这个地方已经说过了，在之后的版本进行修复。

**Comment by JKair** [comment]
@helei112g 好的，谢谢

**Comment by phpyii** [comment]
建议增加微信和支付宝的下载对账单功能

**Comment by helei112g** [comment]
已支持支付宝电脑支付
