### ISSUE TITLE
支付宝即时到账接口现在只支持新的接口了

### ISSUE THREAD

**Issue by jialeo** [helei112g/payment#48]
新申请的支付宝即时到账接口现在只支持新的接口了，现在这个类用不了

**Comment by helei112g** [comment]
即时到账在新的接口变更为：电脑支付，目前sdk还未接入，近期计划中

**Comment by helei112g** [comment]
已接入支付宝 新版本电脑支付 v4.0

**Comment by phpyii** [comment]
666

**Comment by haobingwang** [comment]
👍 使用ok，直接上 rsa2 无压力

**Comment by haobingwang** [comment]
v4.0 貌似有个问题，支付宝不会调用 notify_url ，不知有人遇到过类似的问题么？
