### ISSUE TITLE
打开支付宝网页H5支付会有问题

### ISSUE THREAD

**Issue by haokunjiang** [helei112g/payment#49]
原因是：接口使用的是2.0的接口，但底层的phpSDK使用的还是老的sdk，支付宝那边识别不了，还是按照老的接口返回，结果就给了it_b_pay这个字段，但是客户端新版的sdk是不支持这个it_b_pay字段的，结果就打不开网页支付页面了

**Comment by helei112g** [comment]
说的是新版的电脑支付吧？即原来的即时到账

**Comment by helei112g** [comment]
发现了这个问题，谢谢

**Comment by haokunjiang** [comment]
是手机端打开h5页面的问题
