### ISSUE TITLE
代码贡献讨论

### ISSUE THREAD

**Issue by xzusoft** [helei112g/payment#50]
来一份二开的说明，大家好来增加服务商，比如百付宝、京东支付、翼支付 等等....

**Comment by helei112g** [comment]
好提议。抽时间梳理一下

**Comment by leubao** [comment]
很期待，大家一起完善，速度会快一些，辛苦你做好相应的代码审查就好

**Comment by tangniyuqi** [comment]
支持支持！

**Comment by helei112g** [comment]
@leubao  @tangniyuqi 

贡献说明：https://github.com/helei112g/payment/blob/master/CONTRIBUTING.md

文档部分还没有想好怎么开源。

**Comment by leubao** [comment]
项目结构图是空的

**Comment by helei112g** [comment]
已全部提交

**Comment by 18y** [comment]
里边有什么东西是PHP5.5 不支持的，我鼓捣下

**Comment by helei112g** [comment]
一些新的语法特性。类似： `TestClass::class`    `[]`等

**Comment by idreamsoft** [comment]
我修改了一份 可以在PHP5.3运行的 @helei112g 
https://github.com/idreamsoft/payment

**Comment by helei112g** [comment]
新版本代码指南在readme中
