### ISSUE TITLE
始终提示参数无效

### ISSUE THREAD

**Issue by tangniyuqi** [helei112g/payment#52]
Payment\Common\PayException Object ( [message:protected] => 参数无效

但看不出是哪里问题，配置都检查了好几遍

![z6q0krje808iguxw5k nps1](https://user-images.githubusercontent.com/5830538/27634240-2b3248b2-5c35-11e7-90ff-4a31837bc5d0.png)

**Comment by helei112g** [comment]
传给支付宝的参数错误，仔细对照文档检查传入的参数
