### ISSUE TITLE
沙箱模式扫码支付，返回的url使用qrcode生成二维码只能用测试号扫吗？

### ISSUE THREAD

**Issue by yaobaliu** [helei112g/payment#53]
测试号无法登陆如何测试扫码呢？
https://qr.alipay.com/bax09620fro8v8nuf0pl0049

**Comment by helei112g** [comment]
下载对应的测试app进行登陆

**Comment by yaobaliu** [comment]
就是没有找到沙箱测试app再哪里下载的？地址能不能发一下呢
