### ISSUE TITLE
支付宝微信支付3.x退款方法和2.x版本一样吗？3.x没有文档说明

### ISSUE THREAD

**Issue by yaobaliu** [helei112g/payment#55]
[PHP接入支付宝有密退款接口](https://helei112g.github.io/2016/08/03/PHP接入支付宝有密退款接口/)  ,新版本还是有密接口吗？

**Comment by helei112g** [comment]
不是，新版取消有密退款了，可以看demo。文档还在补全中

**Comment by yaobaliu** [comment]
好的，我是直接composer安装的，没在意demo功能够实现了，万分感谢。
