### ISSUE TITLE
return_param 中含空格会导致验签失败

### ISSUE THREAD

**Issue by Mortence** [helei112g/payment#56]
[教程](https://helei112g.github.io/2017/03/12/Payment%EF%BC%9A%E6%94%AF%E4%BB%98%E5%AE%9D%E6%89%8B%E6%9C%BA%E7%BD%91%E7%AB%99%E6%94%AF%E4%BB%98%E6%95%99%E7%A8%8B/) 中的 return_param 参数中含有空格，会导致验签失败

**Comment by cnbailian** [comment]
我这边看空格是转为 `+` 了

**Comment by Mortence** [comment]
对，我发现了。但是没有细看是库转的，还是支付宝转的

**Comment by helei112g** [comment]
该参数是 payment 进行了urlencode编码，因为支付要对此要求，必须进行编码再进行请求

[支付宝文档地址](https://docs.open.alipay.com/204/105465/)


-- | -- | -- | -- | -- | --
passback_params | String | 否 | 512 | 公用回传参数，如果请求时传递了该参数，则返回给商户时会回传该参数。支付宝会在异步通知时将该参数原样返回。本参数必须进行UrlEncode之后才可以发送给支付宝 | merchantBizType%3d3C%26merchantBizNo%3d2016010101111

**Comment by Mortence** [comment]
多谢解答
