### ISSUE TITLE
return_param参数问题 可以采用 | 、@ 进行分割也报错

### ISSUE THREAD

**Issue by BEIBEI123** [helei112g/payment#58]
支付宝支付，return_param使用123简单字符可以，使用uid|2344@model|expert@mid|1233报错，使用UrlEncode还是报错，json格式也不行，请问应该如何写这个参数

**Comment by helei112g** [comment]
你好，请查看 #52

**Comment by BEIBEI123** [comment]
感谢您的回答，我知道支付宝要求对return_param进行urlencode编码，而payment已处理，也就是说我们传的参数需要要再处理了，现在我有一组数据，比如：uid=15&model=job&mid=10  ，我应该如何写return_param比较合适？我使用了多种隔离方式都并，比如：uid@15|model@job|mid@10，结果报错了，请教我应该如何写？谢谢，除了字母和数字，很多字符我都测试了，只要放入这个字符串就报错

**Comment by BEIBEI123** [comment]
@helei112g 感谢您的回答，我知道支付宝要求对return_param进行urlencode编码，而payment已处理，也就是说我们传的参数需要要再处理了，现在我有一组数据，比如：uid=15&model=job&mid=10 ，我应该如何写return_param比较合适？我使用了多种隔离方式都并，比如：uid@15|model@job|mid@10，结果报错了，请教我应该如何写？谢谢，除了字母和数字，很多字符我都测试了，只要放入这个字符串就报错

**Comment by helei112g** [comment]
可是通过uid-15|model-job|mid-10试一试。
总之避免使用url中可能存在特殊含义的字符。

**Comment by BEIBEI123** [comment]
@helei112g 使用 uid-15|model-job|mid-10 同样也报错误 错误代码 invalid-signature 错误原因: 无效签名
使用uid15这种能正常使用

**Comment by helei112g** [comment]
你尝试，将 `uid-15|model-job|mid-10` 进行base64编码后传入看看验证能够签名通过。
我怀疑支付宝已经限制了这个字段传入一些特殊符号。

**Comment by BEIBEI123** [comment]
谢谢，可以了，我使用的这种加工方式：

`
     //URL 安全的base64编码
    function urlsafe_b64encode($string) {
        $data = base64_encode($string);
        $data = str_replace(array('+','/','='),array('-','_',''),$data);
        return $data;
    }

    //URL 安全的base64解码
    public static function urlsafe_b64decode($string) {
        $data = str_replace(array('-','_'),array('+','/'),$string);
        $mod4 = strlen($data) % 4;
        if ($mod4) {
            $data .= substr('====', $mod4);
        }
        return base64_decode($data);
    }
`
非常感谢您的辛苦付出及热心解答，最后建议您建议一个qq群或微信群，方面大家相互沟通，如果建议了麻烦您在readme中公布下，我们好加入
