### ISSUE TITLE
ALI_CHANNEL_WEB 方式callback错误

### ISSUE THREAD

**Issue by zhongjixiuxing** [helei112g/payment#63]
alipay我采用ALI_CHANNEL_WEB 方式支付成功, alipay服务器callback回到我自己的服务器，然后就出现一个产品 undefined 的错误了（错误截图在下面）. 我追寻源码那度，发现你们是根据alipay的callback返回参数中是否有version字段来处理即时到账的callback，还是其他类型的callback。

![image](https://user-images.githubusercontent.com/8935235/28666300-6254a8dc-72f9-11e7-9843-31a965099c03.png)

**Comment by helei112g** [comment]
请提供下使用的 payment 的版本

**Comment by zhongjixiuxing** [comment]
4.0.1

**Comment by zhongjixiuxing** [comment]
@helei112g 4.0.1
