### ISSUE TITLE
支付宝提示：无效签名，什么原因呢？

### ISSUE THREAD

**Issue by yaobaliu** [helei112g/payment#64]
win下测试正常，正式环境经常出现无效签名问题，请问如何解决呢？

**Comment by helei112g** [comment]
你的提问很奇怪，先是在 win 下测试，又是正式环境，然后又是经常出现。
那意思是有时候出现，有时候不出现？这应该是不可能的。

请重新开一个 issue。交待清楚自己的所用sdk版本。已经自己使用的是哪一个接口，支付宝还是微信或者招商？
