### ISSUE TITLE
阿里 web 支付失败

### ISSUE THREAD

**Issue by Yaojiale** [helei112g/payment#66]
![image](https://user-images.githubusercontent.com/21167327/29052620-d8f388dc-7c1d-11e7-91b0-c42f5c625655.png)
为什么会出现这种情况呢？
以下是我的代码：
![image](https://user-images.githubusercontent.com/21167327/29052662-0b0928f4-7c1e-11e7-95b4-364545f44ee6.png)

**Comment by helei112g** [comment]
检查配置，并确认接口是：web支付还是即时到账支付。
