### ISSUE TITLE
支付宝异步通知TRADE_FINISHED,可能会出现2次异步通知,建议去掉

### ISSUE THREAD

**Issue by yanxuehui** [helei112g/payment#67]
protected function getTradeStatus($status)
    {
        //, 'TRADE_FINISHED'
        if (in_array($status, ['TRADE_SUCCESS', 'TRADE_FINISHED'])) {
            return Config::TRADE_STATUS_SUCC;
        } else {
            return Config::TRADE_STATUS_FAILD;
        }
    }

**Comment by helei112g** [comment]
不太明白你的意思

**Comment by wanmeiwl** [comment]
他的意思是支付宝会做出两次异步通知。即两次请求

**Comment by helei112g** [comment]
@wanmeiwl 谢谢。
@yanxuehui 这是支付宝、微信机制所确定的。
sdk没办法验证是否已经通知过了。应该在自己的回调业务中根据自己系统中订单是否已经因为回调进行了出来来判断。

**Comment by bolechen** [comment]
问题 + 1  cc @helei112g 

给后来的同学提个醒。

`TRADE_FINISHED` 在订单退款成功后，仍然会发通知，所以不能把 `TRADE_FINISHED` 做为成功交易的标志，还需要同时判断 `pay_amount`
