### ISSUE TITLE
payment3 微信扫码支付成功，但退款提示可退款余额不足什么原因？

### ISSUE THREAD

**Issue by yaobaliu** [helei112g/payment#68]
` REFUND_RECHARGE:可用余额退款  REFUND_UNSETTLED:未结算资金退款（默认）`
使用这两个参数都不能成功退款，这个是什么原因呢？微信客服说是我接口调用有问题

**Comment by helei112g** [comment]
微信商户中心后台去设置一下，设置下退款选项，具体你打开看了应该就明白
微信客户骗了你 ~_~

**Comment by yaobaliu** [comment]
是在微信商品平台 》 交易中心 》 交易管理 》 退款配置 中开启   退款结果回调通知吗？ 这个好像是退款成功的异步通知，设置地址还是不行呢

**Comment by helei112g** [comment]
不是，我记得有个退款资金的配置。

**Comment by yaobaliu** [comment]
确定是在微信商户平台设置的，不是在微信公众号平台，是吗？

**Comment by yaobaliu** [comment]
我又用微信支付一单，结果都可以退款，不知道微信搞什么飞机，支付宝从来没有这个问题

**Comment by yaobaliu** [comment]
感谢作者帮助
