### ISSUE TITLE
"代码贡献指南看这里"的链接打开404

### ISSUE THREAD

**Issue by mayne** [helei112g/payment#69]
rt

**Comment by helei112g** [comment]
确定？你在那里点的？我一切正常啊

[不信？你点点看](https://github.com/helei112g/payment/blob/master/CONTRIBUTING.md)

**Comment by mayne** [comment]
@helei112g  sorry, 可能是我没描述清楚问题. readme中 [当前支持的接口](https://github.com/helei112g/payment#当前支持的接口) 这一段最后一句 "提交PR给我，代码贡献指南 看这里", "看这里" 是个链接(https://github.com/helei112g/payment/blob/master/dai-ma-gong-xian.md), 点击打开显示404

**Comment by helei112g** [comment]
已解决。谢谢
