### ISSUE TITLE
支付宝APP端支付

### ISSUE THREAD

**Issue by freedomfly** [helei112g/payment#7]
支付宝APP支付接口，对传递参数支持无序，也就是传递过去什么顺序的参数，直接进行签名和验签，
而我们的程序是统一排序后进行签名，但是实际传递的参数并不是排序后的结果。因此支付宝APP支付应该是实际传递参数进行排序，并且将sign_type 拼接到最后。
AppChargeData.php 改为：$this->retData = ArrayUtil::arraySort(ArrayUtil::paraFilter($signData));  //进行一下排序

AliAppCharge.php  里面的retData() 改为： 
       $data['sign'] =  '"'. urlencode($data['sign']) . '"';
        $signType = $data['sign_type'];
        unset($data['sign_type']);   //去掉sign_type
        $data['sign_type'] = $signType;  //放到最后
        return ArrayUtil::createLinkstring($data);

**Comment by helei112g** [comment]
支付宝文档说支持无序，那么另外也说明支持有序，此处并不影响最终结果。只是为了方便统一处理。非常感谢

**Comment by freedomfly** [comment]
是按有序进行签名的这个没有错，但是因为是无序，传给支付宝什么顺序参数，它不会排序，直接验签，我们这边是将参数数组复制给另一个数组，另一个数组进行排序并且生成签名，但是最终结果是原先的参数数组加签名，而非是有序数组加签名

**Comment by freedomfly** [comment]
同时，由于支付宝不排序，那么sign_type必须放在最后。

**Comment by helei112g** [comment]
哦，你的意思是，app请求的参数是在app上连接好的？没有使用sdk返回的数据？

**Comment by freedomfly** [comment]
不是，就是直接使用retData的结果

**Comment by freedomfly** [comment]
还有就是最后的sign进行完urlencode，要用双引号包裹，因为其它参数都双引号包裹了

**Comment by freedomfly** [comment]
项目不错，我已经用了

**Comment by helei112g** [comment]
我明白你的意思啦：

> 我们这边是将参数数组复制给另一个数组，另一个数组进行排序并且生成签名，但是最终结果是原先的参数数组加签名，而非是有序数组加签名

我看一下如何处理更好。谢谢

**Comment by freedomfly** [comment]
貌似就支付宝APP支付就这一个地方是支持无序的。

**Comment by helei112g** [comment]
是的，但是都可以统一用有序进行处理。这地方可能会让开发者迷糊。后期想办法规避一下。刚好最近可能针对支付宝的新版本进行sdk升级

**Comment by helei112g** [comment]
问题已经通过v2.6 tag解决。谢谢

**Comment by freedomfly** [comment]
good
