### ISSUE TITLE
支付宝的异步通知，为什么就是通过不了签名验证

### ISSUE THREAD

**Issue by jin925** [helei112g/payment#71]
如题，检查了好久代码。没发现什么问题。可以正常的发起支付，完成支付。就是签名验证通过不了。
![image](https://user-images.githubusercontent.com/5148826/29395372-ddb18974-8342-11e7-9d0c-e62fb75c671c.png)

**Comment by helei112g** [comment]
看这里，然后检查下。https://helei112g1.gitbooks.io/payment-sdk/content/faq.html
