### ISSUE TITLE
微信返回错误提示:受理机构必须传入sub_mch_id

### ISSUE THREAD

**Issue by allenlinc** [helei112g/payment#72]
使用特约商户，老报错，可以已经填了，按照DEMO填的

**Comment by allenlinc** [comment]
// 订单信息
$payData = [
    'body'    => 'test body',
    'subject'    => 'test subject',
    'order_no'    => $orderNo,
    'timeout_express' => time() + 600,// 表示必须 600s 内付款
    'amount'    => '3.01',// 微信沙箱模式，需要金额固定为3.01
    'return_param' => '123',
    'client_ip' => isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1',// 客户地址
    'openid' => 'o-e_mwTXTaxEhBM8xDoj1ui1f950',
    'product_id' => '123',

    // 如果是服务商，请提供以下参数
```
   'sub_appid' => '',//微信分配的子商户公众账号ID
    'sub_mch_id' => '',// 微信支付分配的子商户号
    'sub_openid' => '',// 用户在子商户appid下的唯一标识
```
];


   'sub_appid' => '',//微信分配的子商户公众账号ID
    'sub_mch_id' => '',// 微信支付分配的子商户号
    'sub_openid' => '',// 用户在子商户appid下的唯一标识
这3个都填写了，当微信沙箱模式为true可以，但是设置成false就不能用了  
提示：
微信返回错误提示:受理机构必须传入sub_mch_id

**Comment by helei112g** [comment]
微信的什么支付方式？

**Comment by allenlinc** [comment]
微信公众号支付，最基础的。

**Comment by allenlinc** [comment]
前面的wxconfig 里配置的是服务商的appid等信息，paydata里配置的是特约商家的appid等信息，做微信服务号里的支付

**Comment by allenlinc** [comment]
//      'openid' => $openid,   这个不填一定报错
可是特约服务商用的是sub_openid

**Comment by helei112g** [comment]
服务商我后续再检查一下。这部分没有经过线上测试，是直接按照文档来写的。

**Comment by allenlinc** [comment]
期待升级

**Comment by helei112g** [comment]
公众号服务商模式已经支持。麻烦测试下是否可行。
@allenlinc
