### ISSUE TITLE
Alipay配置回调直接返回原始数据，转款成功能直接返回原始数据，但转款失败时仍然直接抛出异常！

### ISSUE THREAD

**Issue by leoxml** [helei112g/payment#73]
在支付宝配置文件aliconfig.php中，设置`return_raw = true`，使用转款功能，成功时能直接返回原始数据；
但转款失败时（收款人与账号不匹配），却仍然直接抛出异常，查看底层代码，发现：
在 `Payment/Trans/AliTransfer.php`中这样处理回调数据
`protected function retData(array $data)
    {
        $url = parent::retData($data);

        try {
            $data = $this->sendReq($url);
        } catch (PayException $e) {
            throw $e;
        }

        if ($this->config->returnRaw) {
            $data['channel'] = Config::ALI_TRANSFER;
            return $data;
        }

        return $this->createBackData($data);
    }`，是否返回原始数据在 `$this->sendReq($url)`之后，而`sendReq()`中，`$body = json_decode($body, true);
        if ($body[$responseKey]['code'] != 10000) {
            throw new PayException($body[$responseKey]['sub_msg']);
        }` 这里直接抛出了异常！
在配置文件中设置“直接返回原始数据”，正常理解就是不管成功失败，返回alipay的原始数据；
但在这里只要是失败就抛出异常，我们并不能根据失败的`sub_code`做进一步的业务处理。
另外，我把这里的抛出异常屏蔽，转款失败后不能通过签名验证，奇怪？
查看过支付宝官方的SDK文件，它是先验签，再返回数据，我觉得这才是正确的顺序；而你们先判断是否失败（`if ($body[$responseKey]['code'] != 10000)`）,再去做验签
希望你们能解惑！！

**Comment by helei112g** [comment]
这是一个高质量问题。**cool**

我之前测试时发现，如果支付出错时，验证签名会报错。根据你的问题，我再次核实发现，错误时验证签名出错，是因为json编码问题。下个版本修复。
