### ISSUE TITLE
关于notify

### ISSUE THREAD

**Issue by hainuo** [helei112g/payment#74]
今天试用了一下 notify  发现一个问题是  并不支持 微信的h5支付  
感觉异步回掉处理应该支持各种方式的校验吧，毕竟校验规则还是比较统一的

**Comment by helei112g** [comment]
你测试完所有的支付，就微信h5支付无法通过吗？有没有报错信息？贴一下。
我代码逻辑支付回调是按照相同的方式进行的处理。

**Comment by hainuo** [comment]
@helei112g  
![image](https://user-images.githubusercontent.com/421861/30091261-5a0a7504-927e-11e7-9522-0186bd1d5d5d.png)
![image](https://user-images.githubusercontent.com/421861/30091309-9e355cee-927e-11e7-9c69-f97e765a7ae3.png)

我看了下源码，是我搞错了通知渠道

我这里提一个建议 notify类的 通知渠道 应该 跟  charge的 渠道 应该统一起来  这样  新手不会搞错了

**Comment by helei112g** [comment]
具体怎么统一？有什么好的想法？
因为在调用回调之前，必须要让调用着告诉我这是哪一个渠道，我才能够init对应的通知服务

**Comment by hainuo** [comment]
我觉得 这里的通知渠道 应该根据付款的渠道来弄
```
class Charge
{
    private static $supportChannel = [
        Config::ALI_CHANNEL_APP,// 支付宝 APP 支付
        Config::ALI_CHANNEL_WAP, // 支付宝手机网页支付
        Config::ALI_CHANNEL_WEB, // 支付宝电脑网站支付
        Config::ALI_CHANNEL_QR, // 支付宝当面付-扫码支付
        Config::ALI_CHANNEL_BAR,// 支付宝当面付-条码支付

        Config::WX_CHANNEL_APP,// 微信 APP 支付
        Config::WX_CHANNEL_PUB,// 微信公众号支付
        Config::WX_CHANNEL_QR,// 微信公众号扫码支付
        Config::WX_CHANNEL_BAR,// 微信刷卡支付
        Config::WX_CHANNEL_WAP,// 微信 WAP 支付（此渠道仅针对特定客户开放）
        Config::WX_CHANNEL_LITE,// 微信小程序支付

        Config::CMB_CHANNEL_APP,// 招行一网通
        'applepay_upacp',// Apple Pay
    ];
}
```
比如跟charge类定义成一样的  或者提出来 统一放到config中   感觉这样 大家就不会为类型 所累了

**Comment by helei112g** [comment]
这样会不会更麻烦？现阶段是回调只需要区分是：支付宝，微信还是招商一网通

如果像你说的这样修改后。那么使用的时候，必须还要区分是具体的哪一种支付？

因为支付、回调这两个动作是分离，不连续的两个动作。在回调过来的时候你怎么区分这个回调是那个支付方式产生的回调呢？

**Comment by chaojiying** [comment]
程序有些地方没看明白，回调notify里面的$type是如何获取到的呢，我看着是写死在demo里面的。
![image](https://user-images.githubusercontent.com/13762645/30198950-08090064-94a3-11e7-9e3c-2754f6d30831.png)

**Comment by helei112g** [comment]
是的，这里需要你们判断回调是来自：支付宝、微信、招商一网通，然后来初始化sdk。

至于如何判断，通常的一种做法是：对三种支付渠道每个提供一个回调支付接口，那么对应的 controller 中便可确定对应的回调来源。

另外一种不常用的方式是，根据回调方的ip来确定。这种方法理论上可行，但我没有实践过，也不推荐。

**Comment by lcp0578** [comment]
@helei112g 您好，我想把订单信息传到notifyProcess这个方法，来进行订单的校验，我看到有如下代码，只是把nofityData传了过去

      ```
 // 回调商户的业务逻辑
        $flag = $this->callback($notify, $notifyData);
```
这块我改怎么灵活的处理下呢？

**Comment by helei112g** [comment]
@lcp0578 订单信息为什要传进来？应该是根据 $notifyData 中的订单号在 db 中查询出订单进行检查。

**Comment by lcp0578** [comment]
@helei112g 我昨天陷入一个误区了，已经实现了，thx
