### ISSUE TITLE
example支付宝转账有问题

### ISSUE THREAD

**Issue by lidelin** [helei112g/payment#76]
1. composer require "riverslei/payment:~4.0.0"
2. cd vendor/riverslei/payment/examples/ali
3. php transfer.php

会报以下错误：
PHP Notice:  Undefined index: alipay_fund_trans_toaccount_transfer_response in /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php on line 97
PHP Stack trace:
PHP   1. {main}() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:0
PHP   2. Payment\Client\Transfer::run() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:29
PHP   3. Payment\TransferContext->transfer() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Client/Transfer.php:66
PHP   4. Payment\Common\Ali\AliBaseStrategy->handle() /home/ldl/work/php/Third/vendor/riverslei/payment/src/TransferContext.php:66
PHP   5. Payment\Trans\AliTransfer->retData() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php:68
PHP   6. Payment\Common\Ali\AliBaseStrategy->sendReq() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Trans/AliTransfer.php:29

Notice: Undefined index: alipay_fund_trans_toaccount_transfer_response in /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php on line 97

Call Stack:
    0.0004     235992   1. {main}() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:0
    0.0031     261384   2. Payment\Client\Transfer::run() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:29
    0.0357     388400   3. Payment\TransferContext->transfer() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Client/Transfer.php:66
    0.0357     388552   4. Payment\Common\Ali\AliBaseStrategy->handle() /home/ldl/work/php/Third/vendor/riverslei/payment/src/TransferContext.php:66
    0.0424     467816   5. Payment\Trans\AliTransfer->retData() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php:68
    0.0425     469104   6. Payment\Common\Ali\AliBaseStrategy->sendReq() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Trans/AliTransfer.php:29

PHP Notice:  Undefined index: alipay_fund_trans_toaccount_transfer_response in /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php on line 98
PHP Stack trace:
PHP   1. {main}() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:0
PHP   2. Payment\Client\Transfer::run() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:29
PHP   3. Payment\TransferContext->transfer() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Client/Transfer.php:66
PHP   4. Payment\Common\Ali\AliBaseStrategy->handle() /home/ldl/work/php/Third/vendor/riverslei/payment/src/TransferContext.php:66
PHP   5. Payment\Trans\AliTransfer->retData() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php:68
PHP   6. Payment\Common\Ali\AliBaseStrategy->sendReq() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Trans/AliTransfer.php:29

Notice: Undefined index: alipay_fund_trans_toaccount_transfer_response in /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php on line 98

Call Stack:
    0.0004     235992   1. {main}() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:0
    0.0031     261384   2. Payment\Client\Transfer::run() /home/ldl/work/php/Third/vendor/riverslei/payment/examples/ali/transfer.php:29
    0.0357     388400   3. Payment\TransferContext->transfer() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Client/Transfer.php:66
    0.0357     388552   4. Payment\Common\Ali\AliBaseStrategy->handle() /home/ldl/work/php/Third/vendor/riverslei/payment/src/TransferContext.php:66
    0.0424     467816   5. Payment\Trans\AliTransfer->retData() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Common/Ali/AliBaseStrategy.php:68
    0.0425     469104   6. Payment\Common\Ali\AliBaseStrategy->sendReq() /home/ldl/work/php/Third/vendor/riverslei/payment/src/Trans/AliTransfer.php:29

**Comment by helei112g** [comment]
demo使用的是沙盒环境，环境并不稳定。会出现一些预料之外的情况。即： **alipay_fund_trans_toaccount_transfer_response** 不存在，正确情况下会返回： 
```
{
    "alipay_fund_trans_toaccount_transfer_response": {
        "code": "10000",
        "msg": "Success",
        "out_biz_no": "3142321423432",
        "order_id": "20160627110070001502260006780837",
        "pay_date": "2013-01-01 08:08:08"
    },
    "sign": "ERITJKEIJKJHKKKKKKKHJEREEEEEEEEEEE"
}
```

如果其沙盒不稳定时，可能有如下问题：
```
{
    "null_response": {
        "code": "20000",
        "msg": "Service Currently Unavailable",
        "sub_code": "aop.unknow-error",
        "sub_msg": "系统繁忙"
    }
}
```

为了确保健壮性，我增加相应判断，防止php语法层面抛出错误

**Comment by lidelin** [comment]
好的
