### ISSUE TITLE
关于微信APP支付文档中配置timeout_express参数时应该传入时间戳。而非date字符串

### ISSUE THREAD

**Issue by fnf1993** [helei112g/payment#78]
```
$params = [
            'body' => $data['body'],
            'subject' => $data['subject'],
            'order_no' => $data['order_no'],
            'amount' => $data['amount'],
            'client_ip' => request()->ip(),
            'timeout_express' => time() + 600
        ];
```
在php7.0.6时按照文档会报错，所以修改未时间戳格式

**Comment by lcp0578** [comment]
@helei112g 我也遇到的同样的时间问题，文档说明有误，

[微信支付的 支付数据](https://helei112g1.gitbooks.io/payment-sdk/content/chapter1/wei-xin.html)

> timeout_express | int(14) | 否 | 订单过期时间，必须大于下单时间5分钟。否则报错，格式：yyyyMMddHHmmss | 20170811175040

源码中，有如下转换

` $this->timeout_express = date('YmdHis', $this->timeout_express);`

望修正文档，thx

**Comment by helei112g** [comment]
已修正。

**Comment by lcp0578** [comment]
thx
