### ISSUE TITLE
我在用3.x版本的时候

### ISSUE THREAD

**Issue by Jhontomson** [helei112g/payment#79]
本地环境5.16.10 MAMP集成的  扩展都具备
在下载下来的阿里云demo的中运行index.html 点入转账操作，http500.
当我尝试用自己的aplipay的key的时候，也不行。虽然钱到账了，但是页面显示http500~

**Comment by helei112g** [comment]
3.x现在没有后续维护。升级到4.1 最新版本试试。

**Comment by Jhontomson** [comment]
我用4.1试了一下，连钱都到不了了- -，还是3.x能到钱，但是显示http500 也就是说$ret 根本没返回 而且也打印不出来相关数据啦。这是什么问题导致的呢，

**Comment by helei112g** [comment]
你好。我本地运行demo测试。4.1 版本可以得到正确结果
```
{
    is_success: "T",
    response: {
        trans_no: "150xxxxxx",
        transaction_id: "2017091511007xxxxxxx",
        pay_date: "2017-09-15 16:15:35",
        channel: "ali_transfer"
    }
}
```

首先你说的 http 500。可以通过断点的方式，查看是程序哪一步抛出了错误来确定原因。

**Comment by Jhontomson** [comment]
你是用composer 然后对其调用还是说下载代码后，直接运行example里面运行的呢。

**Comment by helei112g** [comment]
这两种并不会有什么差别啊？
我是直接运行 example 中的demo。你首先运行demo。如果demo可以通过，而你自己调用无法通过。肯定是你的调用方式存在问题。

**Comment by Jhontomson** [comment]
![2017-09-15 6 58 16](https://user-images.githubusercontent.com/27263086/30479480-03b1a3ae-9a48-11e7-8264-682d3a6d3469.png)
这就是我的结构代码了- -，显示的结果是
![2017-09-15 2 56 52](https://user-images.githubusercontent.com/27263086/30479486-0bddbd74-9a48-11e7-8253-f9915498c407.png)
我是直接用MAMP的， 我就是用的example demo

**Comment by Jhontomson** [comment]
{"is_success":"T","response":{"transaction_id":"20170915110070001502300006101467","trans_no":"1505473355","pay_date":"2017-09-15 19:02:35","channel":"ali_transfer"}}{"is_success":"T","response":{"transaction_id":"20170915110070001502300006101467","trans_no":"1505473355","pay_date":"2017-09-15 19:02:35","channel":"ali_transfer"}}  这是我3.x 版本返回的结果，3.x版本就完美使用~yeah！

**Comment by helei112g** [comment]
我知道你的问题了。payment4.1 拉取后需要composer安装。它依赖了 guzzle 进去网络请求。
payment3.x 是我自己写的一个curl 请求工具，所以可以直接运行。

**Comment by helei112g** [comment]
你期间误导我了。你说 payment3.x 转账能够成功，但是也报 http 500 错误。
