### ISSUE TITLE
GuzzleHttp

### ISSUE THREAD

**Issue by goldencolor** [helei112g/payment#80]
GuzzleHttp 这个是未提供还是怎么了。。thinkphp 3.2使用全部报错

**Comment by helei112g** [comment]
需要 composer 进行安装。它是一个依赖。
`composer install`

**Comment by goldencolor** [comment]
@helei112g 降v3了还有一个问题 ,没有看到微信异步 req_info解码的部分呢？

**Comment by helei112g** [comment]
什么意思？如果是没有收到异步通知，检查下自己的微信后台设置。以及自己服务器的配置。
可以模拟操作一下

**Comment by goldencolor** [comment]
@helei112g 是想问下退款异步通知解码部分在哪里 代码里面没找到呢

**Comment by helei112g** [comment]
微信退款是没有异步通知的。结果是同步返回。
也可以通过退款接口进行查询。

**Comment by goldencolor** [comment]
我们的需求是后台取消退款，然后需要异步去处理整个业务呢

**Comment by helei112g** [comment]
这个与有没有回调通知没有关系。异步可以通过查询退款接口获取结果。
退一万步说，就算微信有退款的异步通知，跟你用不用异步处理也是没有关系的。
