### ISSUE TITLE
sandbox模式下，微信的退款接口，提示＂Undefined index: refund_channel＂

### ISSUE THREAD

**Issue by xlmo** [helei112g/payment#81]
sandbox模式下，微信的退款接口，提示＂Undefined index: refund_channel＂，接口文档中是没有这个返回字段的．  https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_4&index=6．

P.S. 奇怪的是我看这个接口文档里又是有的　https://pay.weixin.qq.com/wiki/doc/api/pap.php?chapter=18_8

**Comment by helei112g** [comment]
将 sdk 的配置文件 `return_raw = false` 修改为： `return_raw=true`

**Comment by xlmo** [comment]
问题解决了，谢谢～
