### ISSUE TITLE
同一个 Request 请求里面如果有多个 Charge::run，第二个返回的结果会不正常

### ISSUE THREAD

**Issue by bolechen** [helei112g/payment#82]
后续所有请求都是第一次的结果
做 UnitTest 的时候发现这个问题，不知道是不是 Charge::run 有特别的处理方式
我稍候贴一个 TestCase 上来
补充：版本 4.1.0

**Comment by bolechen** [comment]
`<?php
/**
 * PaymentTest
 *
 * @group nanrenwa
 * @group nanrenwa.test
 */

use Payment\Common\PayException;
use Payment\Client\Charge;
use Payment\Config;

class PaymentTest extends Kohana_Unittest_TestCase {

    // 订单信息
    var $payData = array (
        'body'    => 'test body',
        'subject'    => 'test subject',
        'amount'    => '3.01',// 微信沙箱模式，需要金额固定为3.01
        'return_param' => '123',
    );

    public function testAlipayWap() {
        $aliConfig = require_once DOCROOT . '/../vendor/riverslei/payment/examples/aliconfig.php';

        $this->payData['order_no'] = time() . rand(1000, 9999);
        $ret = Charge::run(Config::ALI_CHANNEL_WAP, $aliConfig, $this->payData);

        $this->assertContains('https://openapi.alipaydev.com', $ret);
    }

    public function testAlipayQr() {
        $aliConfig = require_once DOCROOT . '/../vendor/riverslei/payment/examples/aliconfig.php';

        $this->payData['order_no'] = time() . rand(1000, 9999);
        $ret = Charge::run(Config::ALI_CHANNEL_QR, $aliConfig, $this->payData);

        $this->assertContains('https://qr.alipay.com/', $ret);
    }
}
`

运行结果如下截图，testAlipayQr 里返回的地址还是 testAlipayWap 里的

![2017-09-19 1 29 30](https://user-images.githubusercontent.com/195015/30577094-9ec7fcdc-9d3e-11e7-9096-8e4ef914087e.png)

**Comment by helei112g** [comment]
稍后我检查下。看起来像是对象被复用的问题。

**Comment by bolechen** [comment]
另外反馈一个问题：最新版本支付宝收不到 notify_url 的异步通知，配置是一样的，回滚到 3.x 正常，具体原因还未查

**Comment by helei112g** [comment]
收不到应该不会吧？确认是收不到，还是处理异步的时候报错了？

**Comment by bolechen** [comment]
但是什么代码都没变，就是用 composer update 更新了版本库，我估计应该是我业务的问题，等我查到再反馈给您。

**Comment by helei112g** [comment]
那我知道了。`mapi.alipay.com` 是即时到账的网关。`open.alipay.com` 是新版电脑支付的网关。可能是这个问题导致的。

**Comment by helei112g** [comment]
@bolechen 后续回调有问题请新开 issue。本问题已修复，发布 4.1.1 版本

**Comment by bolechen** [comment]
@helei112g 
感谢这么快的响应。因为 4.x 版本的 #84 问题，所以我暂时在产品上还用 3.x
我同步改了 3.x 的分支，pull 了，你看对不对
