### ISSUE TITLE
使用sub_openid发送支付请求返回值签名错误

### ISSUE THREAD

**Issue by 806808586** [helei112g/payment#83]
当传递sub_openid发起支付请求的时候返回值的签名还是使用的是服务商的参数做的签名呀
是否可以加个判断

**Comment by helei112g** [comment]
请提供下使用的那一个支付接口？以及使用的微信哪种签名方式？

**Comment by 806808586** [comment]
支付接口是服务商模式小程序支付  签名错误是因为返回数据的appid参数计算时使用的是服务商的 应该使用sub_appid(我直接修改了配置项 不知道还有什么好的办法没有)

**Comment by helei112g** [comment]
可否详细说明下？最后能够贴出代码。我没有服务商的账号。不方便测试

我理解的是，在调起支付那一步的 `app_id` 应该是 `sub_appid` 吗？

**Comment by 806808586** [comment]
对 你理解的对
