### ISSUE TITLE
可以退款么？

### ISSUE THREAD

**Issue by frowhy** [helei112g/payment#88]

**Comment by helei112g** [comment]
可以

**Comment by frowhy** [comment]
没看到怎么用的啊，里面就一个策略类
		

		
	





On Wed, Sep 27, 2017 at 6:41 PM +0800, "大愚" <notifications@github.com> wrote:












可以

**Comment by frowhy** [comment]
不知道该传入什么数据，文档不全。回调好不容易猜出来的怎么写。。。
		

		
	





On Wed, Sep 27, 2017 at 6:41 PM +0800, "大愚" <notifications@github.com> wrote:












可以
