### ISSUE TITLE
支付宝单笔转账的问题

### ISSUE THREAD

**Issue by mynameisdashen** [helei112g/payment#89]
@helei112g 
`提示：支付宝返回数据被篡改。请检查网络是否安全！`
使用的沙箱环境，验签失败会是什么原因呢？

**Comment by helei112g** [comment]
沙箱需要你沙箱应用才可以

**Comment by mynameisdashen** [comment]
@helei112g 
可以详细点吗...转账是成功的，能到账，就是验签时openssl_verify（）返回false失败了，不明白什么原因   T.T

**Comment by helei112g** [comment]
你需要在支付宝开发者平台，拷贝你沙箱应用中，对应的沙箱应用的支付宝公钥进行验证签名。

**Comment by mynameisdashen** [comment]
@helei112g 
抱歉！支付宝公钥被我填成了应用公钥，非常感谢您的提醒！
