### ISSUE TITLE
微信支付-订单查询-返回数据中：trade_state 是大写 SUCCESS

### ISSUE THREAD

**Issue by Lionly** [helei112g/payment#9]
微信支付订单返回值
支付订单中关于 response 中包含字段的描述
trade_state	交易状态	支付成功与否，可取值：success not_pay
遇到的第一个坑，记一下

**Comment by helei112g** [comment]
这里我进行了映射。统一处理为小写。

- success   交易成功
- not_pay  交易未完成
- refund_succ 交易退款成功

**Comment by Lionly** [comment]
文件 payment/src/Query/WxTradeQuery.php 的 85 行
返回数据 'trade_state'   => $data['trade_state'], 这里确实没有做处理，直接返回了 SUCCESS

**Comment by helei112g** [comment]
非常感谢，近期修复

**Comment by helei112g** [comment]
问题在最新开发版本中已经修复。
