### ISSUE TITLE
微信退款异步通知，是否有集成了

### ISSUE THREAD

**Issue by cyfx** [helei112g/payment#90]
如题，最近做微信退款的功能，有个异步通知的渠道，但是好像没有在payment里找到该方式

**Comment by helei112g** [comment]
目前尚未接入，该接口应该是最近才被放出来的。下一个版本支持

**Comment by gyf19** [comment]
@helei112g  这个功能是否已经支持？

**Comment by webxiaohua** [comment]
@helei112g @gyf19  我修改了payment的代码，可以支持微信退款回调，具体如下：
https://github.com/helei112g/payment/pull/186
如果作者暂时不更新，你也可以通过修改这里达到目的

**Comment by helei112g** [comment]
@webxiaohua 感谢，已经合并
