### ISSUE TITLE
支付宝返回数据被篡改。请检查网络是否安全！

### ISSUE THREAD

**Issue by laurelee** [helei112g/payment#97]
执行退款操作时，  已经成功请求，用户也收到钱了，但是页面返回 “支付宝返回数据被篡改。请检查网络是否安全！”，请问这是哪里不对呢，网上检索也没有找到相关问题。

**Comment by helei112g** [comment]
签名验证没有通过。检查自己的支付宝公钥是否正确

**Comment by tangniyuqi** [comment]
@helei112g 我也出现这个问题  支付宝公钥是正确的

**Comment by gracehou** [comment]
我用的时候，也出现过，如果在各种秘钥配置正确的情况下，还报错，可以打印下，sdk中，接收参数并且验证那块代码，项目有没有多余的参数发送回来，多一个参数，签名肯定验证不成功....
