### ISSUE TITLE
微信公众号支付返回的$ret怎么用呢？

### ISSUE THREAD

**Issue by fyrsrelialy** [helei112g/payment#98]
try {
    $ret = Charge::run(Config::WX_CHANNEL_PUB, $wxConfig, $payData);
} catch (PayException $e) {
    echo $e->errorMessage();
    exit;
}

echo $ret;

如代码，这里的$ret在页面中怎么使用呢？
有完整demo吗，谢谢

**Comment by bolechen** [comment]
你都不看手册的嘛，直接跳转或者生成付款二维码
