### ISSUE TITLE
支付宝退款查询接口发现并没有回传refund_reason参数

### ISSUE THREAD

**Issue by flyspring** [helei112g/payment#99]
1.   3.x版本，支付宝退款查询接口AliRefundQuery 中，请求完查询接口后，回传的参数并没有refund_reason，会报错，
$retData = [
            'is_success'    => 'T',
            'response'  => [
                'amount'   => $data['total_amount'],// 订单总金额
                'refund_amount'   => $data['refund_amount'],// 退款金额
                'order_no'   => $data['out_trade_no'],// 商户订单号
                'refund_no' => $data['out_request_no'],// 本笔退款对应的退款请求号
                'transaction_id'   => $data['trade_no'],// 
                **'reason'   => $data['refund_reason'] '',// 这个参数支付宝有时没有回传，会报错**
                'channel'   => Config::ALI_REFUND,
            ]

2.  // 这里有个诡异情况。查询数据全部为空。仅返回一个成功的标记
        if (empty($data['out_trade_no'])) {
            return [
                'is_success'    => 'T',
                'msg'   => strtolower($data['msg']),
                'channel'   => Config::ALI_REFUND,
            ];
        }

经查支付宝文档，文档说是如果还没有退款完成，那么会传空数据，退款成功了才会传 数据。
**文档这么说的**：**该接口的返回码10000，仅代表本次查询操作成功，不代表退款成功。如果该接口返回了查询数据，则代表退款成功，如果没有查询到则代表未退款成功**

**Comment by helei112g** [comment]
下个版本修复该问题
